# coding: utf-8

"""
    AIoD - RAIL

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.20240209-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aiod_rail_sdk.models.environment_var_def import EnvironmentVarDef


class TestEnvironmentVarDef(unittest.TestCase):
    """EnvironmentVarDef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvironmentVarDef:
        """Test EnvironmentVarDef
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `EnvironmentVarDef`
        """
        model = EnvironmentVarDef()
        if include_optional:
            return EnvironmentVarDef(
                name = '',
                description = ''
            )
        else:
            return EnvironmentVarDef(
                name = '',
                description = '',
        )
        """

    def testEnvironmentVarDef(self):
        """Test EnvironmentVarDef"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
