# coding: utf-8

"""
    AIoD - RAIL

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.20240209-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from aiod_rail_sdk.models.location import Location


class TestLocation(unittest.TestCase):
    """Location unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Location:
        """Test Location
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Location`
        """
        model = Location()
        if include_optional:
            return Location(
                address = aiod_rail_sdk.models.address.Address(
                    region = 'California',
                    locality = 'Paris',
                    street = 'Wetstraat 170',
                    postal_code = '1040 AA',
                    country = 'BEL', ),
                geo = aiod_rail_sdk.models.geo.Geo(
                    latitude = 37.42242,
                    longitude = -122.08585,
                    elevation_millimeters = 56, )
            )
        else:
            return Location(
        )
        """

    def testLocation(self):
        """Test Location"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
