# coding: utf-8

"""
    AIoD - RAIL

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.20240507-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aiod_rail_sdk.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_create_or_change_user_api_key_v1_users_api_key_post(self) -> None:
        """Test case for create_or_change_user_api_key_v1_users_api_key_post

        Create Or Change User Api Key
        """
        pass

    def test_get_user_api_key_v1_users_api_key_get(self) -> None:
        """Test case for get_user_api_key_v1_users_api_key_get

        Get User Api Key
        """
        pass

    def test_get_user_profile_v1_users_profile_get(self) -> None:
        """Test case for get_user_profile_v1_users_profile_get

        Get User Profile
        """
        pass


if __name__ == "__main__":
    unittest.main()
