# coding: utf-8

"""
    AIoD - RAIL

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.20240209-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aiod_rail_sdk.api.assets_api import AssetsApi


class TestAssetsApi(unittest.TestCase):
    """AssetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetsApi()

    def tearDown(self) -> None:
        pass

    def test_create_dataset_v1_assets_datasets_post(self) -> None:
        """Test case for create_dataset_v1_assets_datasets_post

        Create Dataset
        """
        pass

    def test_dataset_upload_file_to_huggingface_v1_assets_datasets_id_upload_file_to_huggingface_post(
        self,
    ) -> None:
        """Test case for dataset_upload_file_to_huggingface_v1_assets_datasets_id_upload_file_to_huggingface_post

        Dataset Upload File To Huggingface
        """
        pass

    def test_delete_dataset_v1_assets_datasets_id_delete(self) -> None:
        """Test case for delete_dataset_v1_assets_datasets_id_delete

        Delete Dataset
        """
        pass

    def test_get_dataset_v1_assets_datasets_id_get(self) -> None:
        """Test case for get_dataset_v1_assets_datasets_id_get

        Get Dataset
        """
        pass

    def test_get_datasets_count_v1_assets_counts_datasets_get(self) -> None:
        """Test case for get_datasets_count_v1_assets_counts_datasets_get

        Get Datasets Count
        """
        pass

    def test_get_datasets_v1_assets_datasets_get(self) -> None:
        """Test case for get_datasets_v1_assets_datasets_get

        Get Datasets
        """
        pass

    def test_get_filtered_datasets_count_v1_assets_counts_datasets_search_query_get(
        self,
    ) -> None:
        """Test case for get_filtered_datasets_count_v1_assets_counts_datasets_search_query_get

        Get Filtered Datasets Count
        """
        pass

    def test_get_filtered_models_count_v1_assets_counts_models_search_query_get(
        self,
    ) -> None:
        """Test case for get_filtered_models_count_v1_assets_counts_models_search_query_get

        Get Filtered Models Count
        """
        pass

    def test_get_filtered_publications_count_v1_assets_counts_publications_search_query_get(
        self,
    ) -> None:
        """Test case for get_filtered_publications_count_v1_assets_counts_publications_search_query_get

        Get Filtered Publications Count
        """
        pass

    def test_get_model_v1_assets_models_id_get(self) -> None:
        """Test case for get_model_v1_assets_models_id_get

        Get Model
        """
        pass

    def test_get_models_count_v1_assets_counts_models_get(self) -> None:
        """Test case for get_models_count_v1_assets_counts_models_get

        Get Models Count
        """
        pass

    def test_get_models_v1_assets_models_get(self) -> None:
        """Test case for get_models_v1_assets_models_get

        Get Models
        """
        pass

    def test_get_my_datasets_v1_assets_datasets_my_get(self) -> None:
        """Test case for get_my_datasets_v1_assets_datasets_my_get

        Get My Datasets
        """
        pass

    def test_get_my_models_v1_assets_models_my_get(self) -> None:
        """Test case for get_my_models_v1_assets_models_my_get

        Get My Models
        """
        pass

    def test_get_platforms_v1_assets_platforms_get(self) -> None:
        """Test case for get_platforms_v1_assets_platforms_get

        Get Platforms
        """
        pass

    def test_get_publication_v1_assets_publications_id_get(self) -> None:
        """Test case for get_publication_v1_assets_publications_id_get

        Get Publication
        """
        pass

    def test_get_publications_count_v1_assets_counts_publications_get(self) -> None:
        """Test case for get_publications_count_v1_assets_counts_publications_get

        Get Publications Count
        """
        pass

    def test_get_publications_v1_assets_publications_get(self) -> None:
        """Test case for get_publications_v1_assets_publications_get

        Get Publications
        """
        pass

    def test_search_datasets_v1_assets_datasets_search_query_get(self) -> None:
        """Test case for search_datasets_v1_assets_datasets_search_query_get

        Search Datasets
        """
        pass

    def test_search_models_v1_assets_models_search_query_get(self) -> None:
        """Test case for search_models_v1_assets_models_search_query_get

        Search Models
        """
        pass

    def test_search_publications_v1_assets_publications_search_query_get(self) -> None:
        """Test case for search_publications_v1_assets_publications_search_query_get

        Search Publications
        """
        pass


if __name__ == "__main__":
    unittest.main()
