# coding: utf-8

"""
    AIoD - RAIL

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.20240209-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aiod_rail_sdk.models.runnable_distribution import RunnableDistribution


class TestRunnableDistribution(unittest.TestCase):
    """RunnableDistribution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunnableDistribution:
        """Test RunnableDistribution
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RunnableDistribution`
        """
        model = RunnableDistribution()
        if include_optional:
            return RunnableDistribution(
                platform = 'example',
                platform_resource_identifier = '1',
                checksum = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
                checksum_algorithm = 'sha256',
                copyright = '2010-2020 Example Company. All rights reserved.',
                content_url = 'https://www.example.com/mlmodel/file.csv',
                content_size_kb = 10000,
                date_published = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = 'Description of this file.',
                encoding_format = 'text/csv',
                name = 'Name of this file.',
                technology_readiness_level = 1,
                installation_script = './install.sh',
                installation = 'Build the Dockerfile',
                installation_time_milliseconds = 100,
                deployment_script = './run.sh',
                deployment = 'You can run the run.py file using python3. See README.md for required arguments.',
                deployment_time_milliseconds = 100,
                os_requirement = 'Windows 11.',
                dependency = 'Python packages as listed in requirements.txt.',
                hardware_requirement = '4GB RAM; 100MB storage; 1GHz processor with 8 cores.'
            )
        else:
            return RunnableDistribution(
        )
        """

    def testRunnableDistribution(self):
        """Test RunnableDistribution"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
