# coding: utf-8

"""
    AIoD - RAIL

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.20240209-beta
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest


class TestAssetCardinality(unittest.TestCase):
    """AssetCardinality unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetCardinality(self):
        """Test AssetCardinality"""
        # inst = AssetCardinality()


if __name__ == "__main__":
    unittest.main()
