/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A postal address
 */
export interface Address { 
    /**
     * A subdivision of the country. Not necessary for most countries. 
     */
    region?: any | null;
    /**
     * A city, town or village.
     */
    locality?: any | null;
    /**
     * The street address.
     */
    street?: any | null;
    /**
     * The postal code.
     */
    postal_code?: any | null;
    /**
     * Free text, in case the separate parts such as the street, postal code and country cannot be confidently separated.
     */
    address?: any | null;
    /**
     * The country as ISO 3166-1 alpha-3
     */
    country?: any | null;
}

