/**
 * AIoD Metadata Catalogue
 * This is the Swagger documentation of the AIoD Metadata Catalogue. For the Changelog, refer to <a href=\"https://github.com/aiondemand/AIOD-rest-api/releases\">https://github.com/aiondemand/AIOD-rest-api/releases</a>.
 *
 * The version of the OpenAPI document: 1.2.20231219
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A postal address
 */
export interface Address {
    /**
     * A subdivision of the country. Not necessary for most countries.
     */
    region?: any | null;
    /**
     * A city, town or village.
     */
    locality?: any | null;
    /**
     * The street address.
     */
    street?: any | null;
    /**
     * The postal code.
     */
    postal_code?: any | null;
    /**
     * Free text, in case the separate parts such as the street, postal code and country cannot be confidently separated.
     */
    address?: any | null;
    /**
     * The country as ISO 3166-1 alpha-3
     */
    country?: any | null;
}

