/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Metadata of the metadata: when was the metadata last updated, with what identifiers is it known on other platforms, etc.
 */
export interface AIoDEntryCreate { 
    /**
     * Links to identifiers of persons responsible for maintaining the entry.
     */
    editor?: any | null;
    /**
     * Status of the entry (published, draft, rejected)
     */
    status?: any | null;
}

