/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AIoDEntryRead } from './aio-d-entry-read';


/**
 * The AIoDConcept is the top-level (abstract) class in AIoD.
 */
export interface ContactRead { 
    /**
     * The external platform from which this resource originates. Leave empty if this item originates from AIoD. If platform is not None, the platform_resource_identifier should be set as well.
     */
    platform?: any | null;
    /**
     * A unique identifier issued by the external platform that\'s specified in \'platform\'. Leave empty if this item is not part of an external platform.
     */
    platform_resource_identifier?: any | null;
    name?: any | null;
    aiod_entry?: AIoDEntryRead;
    /**
     * An email address.
     */
    email?: any | null;
    location?: any | null;
    organisation?: any | null;
    person?: any | null;
    /**
     * A telephone number, including the land code.
     */
    telephone?: any | null;
    identifier: any | null;
}

