/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The resulting class, containing a dataset and related entities in the graph
 */
export interface DcatApWrapper { 
  [key: string]: any | any;


    context?: any | null;
    graph: any | null;
}

