/**
 * AIoD Metadata Catalogue
 * This is the Swagger documentation of the AIoD Metadata Catalogue. For the Changelog, refer to <a href=\"https://github.com/aiondemand/AIOD-rest-api/releases\">https://github.com/aiondemand/AIOD-rest-api/releases</a>.
 *
 * The version of the OpenAPI document: 1.3.20240308
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SchemaDotOrgPerson } from './schema-dot-org-person';
import { SchemaDotOrgOrganization } from './schema-dot-org-organization';


/**
 * A person or organization that supports (sponsors) something through some kind of financialcontribution.
 */
export interface Funder { 
    type?: any | null;
    /**
     * The name of the item.
     */
    name: any | null;
    /**
     * Given name. In the U.S., the first name of a Person.
     */
    givenName?: any | null;
    /**
     * Family name. In the U.S., the last name of a Person.
     */
    familyName?: any | null;
}

