/**
 * AIoD Metadata Catalogue
 * This is the Swagger documentation of the AIoD Metadata Catalogue. For the Changelog, refer to <a href=\"https://github.com/aiondemand/AIOD-rest-api/releases\">https://github.com/aiondemand/AIOD-rest-api/releases</a>.
 *
 * The version of the OpenAPI document: 1.2.20231219
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The geographic coordinates of a physical location
 */
export interface Geo {
    /**
     * The latitude of a location in degrees (WGS84)
     */
    latitude?: any | null;
    /**
     * The longitude of a location in degrees (WGS84)
     */
    longitude?: any | null;
    /**
     * The elevation in millimeters with tespect to the WGS84 ellipsoid
     */
    elevation_millimeters?: any | null;
}

