/**
 * AIoD Metadata Catalogue
 * This is the Swagger documentation of the AIoD Metadata Catalogue. For the Changelog, refer to <a href=\"https://github.com/aiondemand/AIOD-rest-api/releases\">https://github.com/aiondemand/AIOD-rest-api/releases</a>.
 *
 * The version of the OpenAPI document: 1.3.20240308
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Distribution } from './distribution';
import { Note } from './note';
import { AIoDEntryCreate } from './aio-d-entry-create';
import { Text } from './text';


/**
 * Many resources, such as organisation and member, are a type of Agent and should therefore inherit from this Agent class. Shared fields can be defined on this class.
 */
export interface OrganisationCreate { 
    /**
     * The external platform from which this resource originates. Leave empty if this item originates from AIoD. If platform is not None, the platform_resource_identifier should be set as well.
     */
    platform?: string;
    /**
     * A unique identifier issued by the external platform that\'s specified in \'platform\'. Leave empty if this item is not part of an external platform. For example, for HuggingFace, this should be the <namespace>/<dataset_name>, and for Openml, the OpenML identifier.
     */
    platform_resource_identifier?: string;
    name: string;
    /**
     * The datetime (utc) on which this resource was first published on an external platform. Note the difference between `.aiod_entry.date_created` and `.date_published`: the former is automatically set to the datetime the resource was created on AIoD, while the latter can optionally be set to an earlier datetime that the resource was published on an external platform.
     */
    date_published?: string;
    /**
     * Url of a reference Web page that unambiguously indicates this resource\'s identity.
     */
    same_as?: string;
    /**
     * The date on which the organisation was founded.
     */
    date_founded?: string;
    /**
     * The official legal name of the organisation.
     */
    legal_name?: string;
    /**
     * A description of positioning of the organisation within the broader European AI ecosystem.
     */
    ai_relevance?: string;
    aiod_entry?: AIoDEntryCreate;
    /**
     * An alias for the item, commonly used for the resource instead of the name.
     */
    alternate_name?: Array<string>;
    /**
     * The objective of this AI resource.
     */
    application_area?: Array<string>;
    /**
     * Contact information of persons/organisations that can be contacted about this resource.
     */
    contact?: Array<number>;
    /**
     * The contact details by which this organisation can be reached
     */
    contact_details?: number;
    /**
     * Contact information of persons/organisations that created this resource.
     */
    creator?: Array<number>;
    description?: Text;
    has_part?: Array<number>;
    /**
     * A business domain where a resource is or can be used.
     */
    industrial_sector?: Array<string>;
    is_part_of?: Array<number>;
    /**
     * Keywords or tags used to describe this resource, providing additional context.
     */
    keyword?: Array<string>;
    /**
     * Images or videos depicting the resource or associated with it. 
     */
    media?: Array<Distribution>;
    /**
     * The identifier of an agent (e.g. organisation or person) that is a member of this organisation.
     */
    member?: Array<number>;
    /**
     * Notes on this AI resource.
     */
    note?: Array<Note>;
    /**
     * URLs of relevant resources. These resources should not be part of AIoD (use relevant_resource otherwise). This field should only be used if there is no more specific field.
     */
    relevant_link?: Array<string>;
    relevant_resource?: Array<number>;
    relevant_to?: Array<number>;
    /**
     * The research area is similar to the scientific_domain, but more high-level.
     */
    research_area?: Array<string>;
    /**
     * The scientific domain is related to the methods with which an objective is reached.
     */
    scientific_domain?: Array<string>;
    /**
     * The type of organisation.
     */
    type?: string;
}

