/**
 * AIoD Metadata Catalogue
 * This is the Swagger documentation of the AIoD Metadata Catalogue. For the Changelog, refer to <a href=\"https://github.com/aiondemand/AIOD-rest-api/releases\">https://github.com/aiondemand/AIOD-rest-api/releases</a>.
 *
 * The version of the OpenAPI document: 1.3.20240308
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventRead } from './event-read';
import { PublicationRead } from './publication-read';
import { ComputationalAssetRead } from './computational-asset-read';
import { Text } from './text';
import { ExperimentRead } from './experiment-read';
import { ProjectRead } from './project-read';
import { OrganisationRead } from './organisation-read';
import { PersonRead } from './person-read';
import { EducationalResourceRead } from './educational-resource-read';
import { MLModelRead } from './ml-model-read';
import { NewsRead } from './news-read';
import { TeamRead } from './team-read';
import { CaseStudyRead } from './case-study-read';
import { DatasetRead } from './dataset-read';
import { ServiceRead } from './service-read';
import { AIoDEntryRead } from './aio-d-entry-read';
import { Location } from './location';


export interface ResponseAiResourceAiResourcesV1IdentifierGet { 
    /**
     * The external platform from which this resource originates. Leave empty if this item originates from AIoD. If platform is not None, the platform_resource_identifier should be set as well.
     */
    platform?: any | null;
    /**
     * A unique identifier issued by the external platform that\'s specified in \'platform\'. Leave empty if this item is not part of an external platform. For example, for HuggingFace, this should be the <namespace>/<dataset_name>, and for Openml, the OpenML identifier.
     */
    platform_resource_identifier?: any | null;
    name: any | null;
    /**
     * The datetime (utc) on which this resource was first published on an external platform. Note the difference between `.aiod_entry.date_created` and `.date_published`: the former is automatically set to the datetime the resource was created on AIoD, while the latter can optionally be set to an earlier datetime that the resource was published on an external platform.
     */
    date_published?: any | null;
    /**
     * Url of a reference Web page that unambiguously indicates this resource\'s identity.
     */
    same_as?: any | null;
    /**
     * The date on which the organisation was founded.
     */
    date_founded?: any | null;
    /**
     * The official legal name of the organisation.
     */
    legal_name?: any | null;
    /**
     * A description of positioning of the organisation within the broader European AI ecosystem.
     */
    ai_relevance?: any | null;
    agent_identifier?: any | null;
    /**
     * This resource can be identified by its own identifier, but also by the resource_identifier.
     */
    ai_resource_identifier?: any | null;
    aiod_entry?: AIoDEntryRead;
    /**
     * An alias for the item, commonly used for the resource instead of the name.
     */
    alternate_name?: any | null;
    /**
     * The objective of this AI resource.
     */
    application_area?: any | null;
    /**
     * Contact information of persons/organisations that can be contacted about this resource.
     */
    contact?: any | null;
    /**
     * The contact details by which this person can be reached
     */
    contact_details?: any | null;
    /**
     * Contact information of persons/organisations that created this resource.
     */
    creator?: any | null;
    description?: Text;
    has_part?: any | null;
    /**
     * A business domain where a resource is or can be used.
     */
    industrial_sector?: any | null;
    is_part_of?: any | null;
    /**
     * Keywords or tags used to describe this resource, providing additional context.
     */
    keyword?: any | null;
    /**
     * Images or videos depicting the resource or associated with it. 
     */
    media?: any | null;
    /**
     * The persons that are a member of this team. The leader should also be added as contact.
     */
    member?: any | null;
    /**
     * Notes on this AI resource.
     */
    note?: any | null;
    /**
     * URLs of relevant resources. These resources should not be part of AIoD (use relevant_resource otherwise). This field should only be used if there is no more specific field.
     */
    relevant_link?: any | null;
    relevant_resource?: any | null;
    relevant_to?: any | null;
    /**
     * The research area is similar to the scientific_domain, but more high-level.
     */
    research_area?: any | null;
    /**
     * The scientific domain is related to the methods with which an objective is reached.
     */
    scientific_domain?: any | null;
    /**
     * The type of educational resource.
     */
    type?: any | null;
    identifier: any | null;
    /**
     * Also known as forename or first name. The part of the personal name that identifies a person, potentially with a middle name as well.
     */
    given_name?: any | null;
    /**
     * Also known as last name or family name. The mostly hereditary part of the personal name.
     */
    surname?: any | null;
    /**
     * A ballpark figure of the per hour cost to hire this team.
     */
    price_per_hour_euro?: any | null;
    /**
     * Does this person want to be contacted about new opportunities relating their expertise?
     */
    wants_to_be_contacted?: any | null;
    /**
     * A skill this person masters.
     */
    expertise?: any | null;
    /**
     * A language this person masters, in ISO639-3
     */
    language?: any | null;
    /**
     * A flag to signal that this asset is accessible at no cost.
     */
    is_accessible_for_free?: any | null;
    /**
     * The version of this asset.
     */
    version?: any | null;
    /**
     * The International Standard Serial Number, ISSN, an identifier for serial publications.
     */
    issn?: any | null;
    /**
     * The technique, technology, or methodology used in a dataset, corresponding to the method used for measuring the corresponding variable(s).
     */
    measurement_technique?: any | null;
    /**
     * The temporalCoverage of a CreativeWork indicates the period that the content applies to, i.e. that it describes, a textual string indicating a time period in ISO 8601 time interval format. In the case of a Dataset it will typically indicate the relevant time period in a precise notation (e.g. for a 2011 census dataset, the year 2011 would be written \'2011/2012\').
     */
    temporal_coverage?: any | null;
    ai_asset_identifier?: any | null;
    /**
     * A bibliographic reference.
     */
    citation?: any | null;
    distribution?: any | null;
    /**
     * Identifiers of organizations that support this project through some kind of financial contribution. 
     */
    funder?: any | null;
    license?: any | null;
    /**
     * The number of persons that are part of this team.
     */
    size?: any | null;
    /**
     * A location that describes the spatial aspect of this dataset. For example, a point where all the measurements were collected.
     */
    spatial_coverage?: Location;
    /**
     * A Permanent Identifier (e.g. DOI) for the entity
     */
    permanent_identifier?: any | null;
    /**
     * The International Standard Book Number, ISBN, used to identify published books or, more rarely, journal issues.
     */
    isbn?: any | null;
    content?: Text;
    /**
     * The identifier of an AI asset for which the Knowledge Asset acts as an information source
     */
    documents?: any | null;
    /**
     * A webpage that shows the current status of this asset.
     */
    status_info?: any | null;
    /**
     * A permanent identifier for the model, for example a digital object identifier (DOI). Ideally a url.
     */
    pid?: any | null;
    /**
     * A human readable description of the overall workflow of the experiment.
     */
    experimental_workflow?: any | null;
    /**
     * A human-readable description of the settings under which the experiment was executed.
     */
    execution_settings?: any | null;
    /**
     * A description of how the output of the experiment matches the experiments in the paper.
     */
    reproducibility_explanation?: any | null;
    /**
     * Labels awarded on the basis of the reproducibility of this experiment.
     */
    badge?: any | null;
    /**
     * Related experiments.
     */
    related_experiment?: any | null;
    /**
     * An approximate or recommendation of the time required to use or complete the educational resource.
     */
    time_required?: any | null;
    /**
     * The primary mode of accessing this educational resource.
     */
    access_mode?: any | null;
    /**
     * The level or levels of education for which this resource is intended.
     */
    educational_level?: any | null;
    /**
     * The language(s) of the educational resource, in ISO639-3.
     */
    in_language?: any | null;
    location?: any | null;
    /**
     * The high-level study schedule available for this educational resource. \"self-paced\" is mostly used for MOOCS, Tutorials and short courses without interactive elements; \"scheduled\" is used for scheduled courses with interactive elements that is not a full-time engagement; \"full-time\" is used for programmes or intensive courses that require a full-time engagement from the student.
     */
    pace?: any | null;
    /**
     * Minimum or recommended requirements to make use of this educational resource.
     */
    prerequisite?: any | null;
    /**
     * The intended users of this educational resource.
     */
    target_audience?: any | null;
    /**
     * The start date and time of the project as ISO 8601.
     */
    start_date?: any | null;
    /**
     * The end date and time of the project as ISO 8601.
     */
    end_date?: any | null;
    /**
     * The agenda of the event.
     */
    schedule?: any | null;
    /**
     * The url of the registration form.
     */
    registration_link?: any | null;
    /**
     * The attendance mode of event.
     */
    mode?: any | null;
    /**
     * The person or organisation responsible for organising the event.
     */
    organiser?: any | null;
    /**
     * Links to identifiers of the agents (person or organization) that is contributing to this event 
     */
    performer?: any | null;
    /**
     * The status of the event.
     */
    status?: any | null;
    /**
     * A short headline given to this news item.
     */
    headline?: any | null;
    /**
     * An alternative headline given to this news item.
     */
    alternative_headline?: any | null;
    /**
     * News categories related to this item.
     */
    category?: any | null;
    /**
     * The total budget of the project in euros.
     */
    total_cost_euro?: any | null;
    /**
     * The coordinating organisation of this project.
     */
    coordinator?: any | null;
    /**
     * Identifiers of members of this project. 
     */
    participant?: any | null;
    /**
     * Identifiers of AIAssets that are created in this project.
     */
    produced?: any | null;
    /**
     * Identifiers of AIAssets that are used (but not created) in this project.
     */
    used?: any | null;
    /**
     * A slogan or motto associated with the service.
     */
    slogan?: any | null;
    /**
     * Human-readable terms of service documentation.
     */
    terms_of_service?: any | null;
    /**
     * The organisation of which this team is a part.
     */
    organisation?: any | null;
}

