/**
 * AIoD Metadata Catalogue
 * This is the Swagger documentation of the AIoD Metadata Catalogue. For the Changelog, refer to <a href=\"https://github.com/aiondemand/AIOD-rest-api/releases\">https://github.com/aiondemand/AIOD-rest-api/releases</a>.
 *
 * The version of the OpenAPI document: 1.3.20240308
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A person (alive, dead, undead, or fictional).  See: https://schema.org/Person
 */
export interface SchemaDotOrgPerson { 
    type?: string;
    /**
     * The name of the item.
     */
    name: string;
    /**
     * Given name. In the U.S., the first name of a Person.
     */
    givenName?: string;
    /**
     * Family name. In the U.S., the last name of a Person.
     */
    familyName?: string;
}

