/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A person (alive, dead, undead, or fictional).  See: https://schema.org/Person
 */
export interface SchemaDotOrgPerson { 
    type?: any | null;
    /**
     * The name of the item.
     */
    name: any | null;
    /**
     * Given name. In the U.S., the first name of a Person.
     */
    givenName?: any | null;
    /**
     * Family name. In the U.S., the last name of a Person.
     */
    familyName?: any | null;
}

