/**
 * AIoD Metadata Catalogue
 * This is the Swagger documentation of the AIoD Metadata Catalogue. For the Changelog, refer to <a href=\"https://github.com/aiondemand/AIOD-rest-api/releases\">https://github.com/aiondemand/AIOD-rest-api/releases</a>.
 *
 * The version of the OpenAPI document: 1.2.20231219
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A dataset in downloadable form.  See: https://schema.org/DataDownload
 */
export interface SchemaDotOrgDataDownload {
    type?: any | null;
    /**
     * The name of the item.
     */
    name?: any | null;
    /**
     * Actual bytes of the media object, for example the image file or video file.
     */
    contentUrl: any | null;
    /**
     * File size in (mega/kilo) bytes.
     */
    contentSize?: any | null;
    /**
     * Media type typically expressed using a MIME format (see [IANA site](http://www.iana.org/assignments/media-types/media-types.xhtml) and [MDN reference](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types))e.g. application/zip for a SoftwareApplication binary, audio/mpeg for .mp3 etc.).In cases where a [[CreativeWork]] has several media type representations, [[encoding]]can be used to indicate each [[MediaObject]] alongside particular [[encodingFormat]]information. Unregistered or niche encoding and file formats can be indicated insteadvia the most appropriate URL, e.g. defining Web page or a Wikipedia/Wikidata entry.
     */
    encodingFormat?: any | null;
}

