/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An organization such as a school, NGO, corporation, club, etc.  See: https://schema.org/Organization
 */
export interface SchemaDotOrgOrganization { 
    type?: any | null;
    /**
     * The name of the item.
     */
    name: any | null;
}

