# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class AIoDEntryCreate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AIoDEntryCreate - a model defined in OpenAPI

        editor: The editor of this AIoDEntryCreate [Optional].
        status: The status of this AIoDEntryCreate [Optional].
    """

    editor: Optional[List[int]] = Field(alias="editor", default=None)
    status: Optional[str] = Field(alias="status", default=None)


AIoDEntryCreate.update_forward_refs()
