# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Checksum(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Checksum - a model defined in OpenAPI

        value: The value of this Checksum.
        algorithm: The algorithm of this Checksum.
    """

    value: str = Field(alias="value")
    algorithm: str = Field(alias="algorithm")

    @validator("value")
    def value_max_length(cls, value):
        assert len(value) <= 500
        return value

Checksum.update_forward_refs()
