# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

from app.schemas.aiod_generated.aio_d_entry_create import AIoDEntryCreate


class ComputationalAssetCreate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ComputationalAssetCreate - a model defined in OpenAPI

        platform: The platform of this ComputationalAssetCreate [Optional].
        platform_identifier: The platform_identifier of this ComputationalAssetCreate [Optional].
        name: The name of this ComputationalAssetCreate.
        description: The description of this ComputationalAssetCreate [Optional].
        same_as: The same_as of this ComputationalAssetCreate [Optional].
        date_published: The date_published of this ComputationalAssetCreate [Optional].
        is_accessible_for_free: The is_accessible_for_free of this ComputationalAssetCreate [Optional].
        version: The version of this ComputationalAssetCreate [Optional].
        status_info: The status_info of this ComputationalAssetCreate [Optional].
        aiod_entry: The aiod_entry of this ComputationalAssetCreate [Optional].
        alternate_name: The alternate_name of this ComputationalAssetCreate [Optional].
        application_area: The application_area of this ComputationalAssetCreate [Optional].
        citation: The citation of this ComputationalAssetCreate [Optional].
        contact: The contact of this ComputationalAssetCreate [Optional].
        creator: The creator of this ComputationalAssetCreate [Optional].
        distribution: The distribution of this ComputationalAssetCreate [Optional].
        has_part: The has_part of this ComputationalAssetCreate [Optional].
        industrial_sector: The industrial_sector of this ComputationalAssetCreate [Optional].
        is_part_of: The is_part_of of this ComputationalAssetCreate [Optional].
        keyword: The keyword of this ComputationalAssetCreate [Optional].
        license: The license of this ComputationalAssetCreate [Optional].
        media: The media of this ComputationalAssetCreate [Optional].
        note: The note of this ComputationalAssetCreate [Optional].
        research_area: The research_area of this ComputationalAssetCreate [Optional].
        scientific_domain: The scientific_domain of this ComputationalAssetCreate [Optional].
        type: The type of this ComputationalAssetCreate [Optional].
    """

    platform: Optional[object] = Field(alias="platform", default=None)
    platform_identifier: Optional[object] = Field(
        alias="platform_identifier", default=None
    )
    name: object = Field(alias="name")
    description: Optional[object] = Field(alias="description", default=None)
    same_as: Optional[object] = Field(alias="same_as", default=None)
    date_published: Optional[object] = Field(alias="date_published", default=None)
    is_accessible_for_free: Optional[object] = Field(
        alias="is_accessible_for_free", default=None
    )
    version: Optional[object] = Field(alias="version", default=None)
    status_info: Optional[object] = Field(alias="status_info", default=None)
    aiod_entry: Optional[AIoDEntryCreate] = Field(alias="aiod_entry", default=None)
    alternate_name: Optional[object] = Field(alias="alternate_name", default=None)
    application_area: Optional[object] = Field(alias="application_area", default=None)
    citation: Optional[object] = Field(alias="citation", default=None)
    contact: Optional[object] = Field(alias="contact", default=None)
    creator: Optional[object] = Field(alias="creator", default=None)
    distribution: Optional[object] = Field(alias="distribution", default=None)
    has_part: Optional[object] = Field(alias="has_part", default=None)
    industrial_sector: Optional[object] = Field(alias="industrial_sector", default=None)
    is_part_of: Optional[object] = Field(alias="is_part_of", default=None)
    keyword: Optional[object] = Field(alias="keyword", default=None)
    license: Optional[object] = Field(alias="license", default=None)
    media: Optional[object] = Field(alias="media", default=None)
    note: Optional[object] = Field(alias="note", default=None)
    research_area: Optional[object] = Field(alias="research_area", default=None)
    scientific_domain: Optional[object] = Field(alias="scientific_domain", default=None)
    type: Optional[object] = Field(alias="type", default=None)

    @validator("platform")
    def platform_max_length(cls, value):
        assert len(value) <= 64
        return value

    @validator("platform_identifier")
    def platform_identifier_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("name")
    def name_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("description")
    def description_max_length(cls, value):
        assert len(value) <= 1800
        return value

    @validator("same_as")
    def same_as_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("version")
    def version_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("status_info")
    def status_info_max_length(cls, value):
        assert len(value) <= 256
        return value


ComputationalAssetCreate.update_forward_refs()
