# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

from app.schemas.aiod_generated.computational_resource_distribution import (
    ComputationalResourceDistribution,
)


class ComputationalResourceCreate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ComputationalResourceCreate - a model defined in OpenAPI

        platform: The platform of this ComputationalResourceCreate [Optional].
        platform_identifier: The platform_identifier of this ComputationalResourceCreate [Optional].
        name: The name of this ComputationalResourceCreate.
        description: The description of this ComputationalResourceCreate [Optional].
        logo: The logo of this ComputationalResourceCreate [Optional].
        creation_time: The creation_time of this ComputationalResourceCreate [Optional].
        validity: The validity of this ComputationalResourceCreate [Optional].
        complexity: The complexity of this ComputationalResourceCreate [Optional].
        location: The location of this ComputationalResourceCreate [Optional].
        type: The type of this ComputationalResourceCreate [Optional].
        quality_level: The quality_level of this ComputationalResourceCreate [Optional].
        alternate_name: The alternate_name of this ComputationalResourceCreate.
        capability: The capability of this ComputationalResourceCreate.
        citation: The citation of this ComputationalResourceCreate.
        keyword: The keyword of this ComputationalResourceCreate.
        other_info: The other_info of this ComputationalResourceCreate.
        research_area: The research_area of this ComputationalResourceCreate.
        application_area: The application_area of this ComputationalResourceCreate.
        is_part_of: The is_part_of of this ComputationalResourceCreate.
        has_part: The has_part of this ComputationalResourceCreate.
        creator: The creator of this ComputationalResourceCreate.
        contact: The contact of this ComputationalResourceCreate.
        managed_by: The managed_by of this ComputationalResourceCreate.
        distribution: The distribution of this ComputationalResourceCreate.
        status_info: The status_info of this ComputationalResourceCreate.
        has_share: The has_share of this ComputationalResourceCreate.
        service: The service of this ComputationalResourceCreate.
        has_endpoint: The has_endpoint of this ComputationalResourceCreate.
    """

    platform: Optional[str] = Field(alias="platform", default=None)
    platform_identifier: Optional[str] = Field(
        alias="platform_identifier", default=None
    )
    name: str = Field(alias="name")
    description: Optional[str] = Field(alias="description", default=None)
    logo: Optional[str] = Field(alias="logo", default=None)
    creation_time: Optional[datetime] = Field(alias="creationTime", default=None)
    validity: Optional[int] = Field(alias="validity", default=None)
    complexity: Optional[str] = Field(alias="complexity", default=None)
    location: Optional[str] = Field(alias="location", default=None)
    type: Optional[str] = Field(alias="type", default=None)
    quality_level: Optional[str] = Field(alias="qualityLevel", default=None)
    alternate_name: List[str] = Field(alias="alternateName")
    capability: List[str] = Field(alias="capability")
    citation: List[str] = Field(alias="citation")
    keyword: List[str] = Field(alias="keyword")
    other_info: List[str] = Field(alias="otherInfo")
    research_area: List[str] = Field(alias="researchArea")
    application_area: List[str] = Field(alias="applicationArea")
    is_part_of: List[int] = Field(alias="isPartOf")
    has_part: List[int] = Field(alias="hasPart")
    creator: List[int] = Field(alias="creator")
    contact: List[int] = Field(alias="contact")
    managed_by: List[int] = Field(alias="managedBy")
    distribution: List[ComputationalResourceDistribution] = Field(alias="distribution")
    status_info: List[str] = Field(alias="statusInfo")
    has_share: List[str] = Field(alias="hasShare")
    service: List[str] = Field(alias="service")
    has_endpoint: List[str] = Field(alias="hasEndpoint")

    @validator("name")
    def name_max_length(cls, value):
        assert len(value) <= 150
        return value

    @validator("description")
    def description_max_length(cls, value):
        assert len(value) <= 5000
        return value

    @validator("logo")
    def logo_max_length(cls, value):
        assert len(value) <= 250
        return value

    @validator("complexity")
    def complexity_max_length(cls, value):
        assert len(value) <= 250
        return value

    @validator("location")
    def location_max_length(cls, value):
        assert len(value) <= 500
        return value

    @validator("type")
    def type_max_length(cls, value):
        assert len(value) <= 500
        return value

    @validator("quality_level")
    def quality_level_max_length(cls, value):
        assert len(value) <= 500
        return value


ComputationalResourceCreate.update_forward_refs()
