# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

from app.schemas.aiod_generated.creator_any_of_inner import CreatorAnyOfInner
from app.schemas.aiod_generated.schema_dot_org_organization import (
    SchemaDotOrgOrganization,
)
from app.schemas.aiod_generated.schema_dot_org_person import SchemaDotOrgPerson


class Creator(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Creator - a model defined in OpenAPI

        type: The type of this Creator [Optional].
        name: The name of this Creator.
    """

    type: Optional[str] = Field(alias="@type", default=None)
    name: str = Field(alias="name")


Creator.update_forward_refs()
