# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class DcatLocation(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DcatLocation - a model defined in OpenAPI

        id: The id of this DcatLocation.
        type: The type of this DcatLocation [Optional].
        dcatbbox: The dcatbbox of this DcatLocation [Optional].
        dcatcentroid: The dcatcentroid of this DcatLocation [Optional].
        dcatgeometry: The dcatgeometry of this DcatLocation [Optional].
    """

    id: str = Field(alias="@id")
    type: Optional[str] = Field(alias="@type", default=None)
    dcatbbox: Optional[str] = Field(alias="dcat:bbox", default=None)
    dcatcentroid: Optional[str] = Field(alias="dcat:centroid", default=None)
    dcatgeometry: Optional[str] = Field(alias="dcat:geometry", default=None)

DcatLocation.update_forward_refs()
