# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

from app.schemas.aiod_generated.dcat_ap_identifier import DcatAPIdentifier


class DcatAPDistribution(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DcatAPDistribution - a model defined in OpenAPI

        id: The id of this DcatAPDistribution.
        type: The type of this DcatAPDistribution [Optional].
        dcataccess_url: The dcataccess_url of this DcatAPDistribution [Optional].
        dcatbyte_size: The dcatbyte_size of this DcatAPDistribution [Optional].
        spdxchecksum: The spdxchecksum of this DcatAPDistribution [Optional].
        dctdescription: The dctdescription of this DcatAPDistribution [Optional].
        dcatdownload_url: The dcatdownload_url of this DcatAPDistribution [Optional].
        dctformat: The dctformat of this DcatAPDistribution [Optional].
        dctlicense: The dctlicense of this DcatAPDistribution [Optional].
        dcttitle: The dcttitle of this DcatAPDistribution [Optional].
    """

    id: str = Field(alias="@id")
    type: Optional[str] = Field(alias="@type", default=None)
    dcataccess_url: Optional[str] = Field(alias="dcat:accessURL", default=None)
    dcatbyte_size: Optional[int] = Field(alias="dcat:byteSize", default=None)
    spdxchecksum: Optional[DcatAPIdentifier] = Field(
        alias="spdx:checksum", default=None
    )
    dctdescription: Optional[str] = Field(alias="dct:description", default=None)
    dcatdownload_url: Optional[str] = Field(alias="dcat:downloadURL", default=None)
    dctformat: Optional[str] = Field(alias="dct:format", default=None)
    dctlicense: Optional[str] = Field(alias="dct:license", default=None)
    dcttitle: Optional[str] = Field(alias="dct:title", default=None)


DcatAPDistribution.update_forward_refs()
