# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class DcatApWrapper(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DcatApWrapper - a model defined in OpenAPI

        context: The context of this DcatApWrapper [Optional].
        graph: The graph of this DcatApWrapper.
    """

    context: Optional[object] = Field(alias="@context", default=None)
    graph: object = Field(alias="@graph")


DcatApWrapper.update_forward_refs()
