# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from app.schemas.aiod_generated.xsd_date_time import XSDDateTime


class DctPeriodOfTime(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DctPeriodOfTime - a model defined in OpenAPI

        id: The id of this DctPeriodOfTime.
        type: The type of this DctPeriodOfTime [Optional].
        dcatstart_date: The dcatstart_date of this DctPeriodOfTime [Optional].
        dcatend_date: The dcatend_date of this DctPeriodOfTime [Optional].
    """

    id: str = Field(alias="@id")
    type: Optional[str] = Field(alias="@type", default=None)
    dcatstart_date: Optional[XSDDateTime] = Field(alias="dcat:startDate", default=None)
    dcatend_date: Optional[XSDDateTime] = Field(alias="dcat:endDate", default=None)

DctPeriodOfTime.update_forward_refs()
