# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Distribution(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Distribution - a model defined in OpenAPI

        platform: The platform of this Distribution [Optional].
        platform_identifier: The platform_identifier of this Distribution [Optional].
        checksum: The checksum of this Distribution [Optional].
        checksum_algorithm: The checksum_algorithm of this Distribution [Optional].
        copyright: The copyright of this Distribution [Optional].
        content_url: The content_url of this Distribution.
        content_size_kb: The content_size_kb of this Distribution [Optional].
        date_published: The date_published of this Distribution [Optional].
        description: The description of this Distribution [Optional].
        encoding_format: The encoding_format of this Distribution [Optional].
        name: The name of this Distribution [Optional].
        technology_readiness_level: The technology_readiness_level of this Distribution [Optional].
    """

    platform: Optional[str] = Field(alias="platform", default=None)
    platform_identifier: Optional[str] = Field(
        alias="platform_identifier", default=None
    )
    checksum: Optional[str] = Field(alias="checksum", default=None)
    checksum_algorithm: Optional[str] = Field(alias="checksum_algorithm", default=None)
    copyright: Optional[str] = Field(alias="copyright", default=None)
    content_url: str = Field(alias="content_url")
    content_size_kb: Optional[int] = Field(alias="content_size_kb", default=None)
    date_published: Optional[datetime] = Field(alias="date_published", default=None)
    description: Optional[str] = Field(alias="description", default=None)
    encoding_format: Optional[str] = Field(alias="encoding_format", default=None)
    name: Optional[str] = Field(alias="name", default=None)
    technology_readiness_level: Optional[int] = Field(
        alias="technology_readiness_level", default=None
    )

    @validator("platform")
    def platform_max_length(cls, value):
        assert len(value) <= 64
        return value

    @validator("platform_identifier")
    def platform_identifier_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("checksum")
    def checksum_max_length(cls, value):
        assert len(value) <= 1800
        return value

    @validator("checksum_algorithm")
    def checksum_algorithm_max_length(cls, value):
        assert len(value) <= 64
        return value

    @validator("copyright")
    def copyright_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("content_url")
    def content_url_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("description")
    def description_max_length(cls, value):
        assert len(value) <= 1800
        return value

    @validator("encoding_format")
    def encoding_format_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("name")
    def name_max_length(cls, value):
        assert len(value) <= 256
        return value


Distribution.update_forward_refs()
