# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

from app.schemas.aiod_generated.schema_dot_org_data_download import (
    SchemaDotOrgDataDownload,
)


class Distribution1(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Distribution1 - a model defined in OpenAPI

        type: The type of this Distribution1 [Optional].
        name: The name of this Distribution1 [Optional].
        content_url: The content_url of this Distribution1.
        content_size: The content_size of this Distribution1 [Optional].
        encoding_format: The encoding_format of this Distribution1 [Optional].
    """

    type: Optional[str] = Field(alias="@type", default=None)
    name: Optional[str] = Field(alias="name", default=None)
    content_url: str = Field(alias="contentUrl")
    content_size: Optional[str] = Field(alias="contentSize", default=None)
    encoding_format: Optional[str] = Field(alias="encodingFormat", default=None)


Distribution1.update_forward_refs()
