# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

from app.schemas.aiod_generated.aio_d_entry_create import AIoDEntryCreate


class EducationalResourceCreate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EducationalResourceCreate - a model defined in OpenAPI

        platform: The platform of this EducationalResourceCreate [Optional].
        platform_identifier: The platform_identifier of this EducationalResourceCreate [Optional].
        name: The name of this EducationalResourceCreate.
        description: The description of this EducationalResourceCreate [Optional].
        same_as: The same_as of this EducationalResourceCreate [Optional].
        level: The level of this EducationalResourceCreate [Optional].
        aiod_entry: The aiod_entry of this EducationalResourceCreate [Optional].
        alternate_name: The alternate_name of this EducationalResourceCreate [Optional].
        application_area: The application_area of this EducationalResourceCreate [Optional].
        contact: The contact of this EducationalResourceCreate [Optional].
        has_part: The has_part of this EducationalResourceCreate [Optional].
        industrial_sector: The industrial_sector of this EducationalResourceCreate [Optional].
        is_part_of: The is_part_of of this EducationalResourceCreate [Optional].
        keyword: The keyword of this EducationalResourceCreate [Optional].
        media: The media of this EducationalResourceCreate [Optional].
        note: The note of this EducationalResourceCreate [Optional].
        research_area: The research_area of this EducationalResourceCreate [Optional].
        scientific_domain: The scientific_domain of this EducationalResourceCreate [Optional].
        type: The type of this EducationalResourceCreate [Optional].
    """

    platform: Optional[object] = Field(alias="platform", default=None)
    platform_identifier: Optional[object] = Field(
        alias="platform_identifier", default=None
    )
    name: object = Field(alias="name")
    description: Optional[object] = Field(alias="description", default=None)
    same_as: Optional[object] = Field(alias="same_as", default=None)
    level: Optional[object] = Field(alias="level", default=None)
    aiod_entry: Optional[AIoDEntryCreate] = Field(alias="aiod_entry", default=None)
    alternate_name: Optional[object] = Field(alias="alternate_name", default=None)
    application_area: Optional[object] = Field(alias="application_area", default=None)
    contact: Optional[object] = Field(alias="contact", default=None)
    has_part: Optional[object] = Field(alias="has_part", default=None)
    industrial_sector: Optional[object] = Field(alias="industrial_sector", default=None)
    is_part_of: Optional[object] = Field(alias="is_part_of", default=None)
    keyword: Optional[object] = Field(alias="keyword", default=None)
    media: Optional[object] = Field(alias="media", default=None)
    note: Optional[object] = Field(alias="note", default=None)
    research_area: Optional[object] = Field(alias="research_area", default=None)
    scientific_domain: Optional[object] = Field(alias="scientific_domain", default=None)
    type: Optional[object] = Field(alias="type", default=None)

    @validator("platform")
    def platform_max_length(cls, value):
        assert len(value) <= 64
        return value

    @validator("platform_identifier")
    def platform_identifier_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("name")
    def name_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("description")
    def description_max_length(cls, value):
        assert len(value) <= 1800
        return value

    @validator("same_as")
    def same_as_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("level")
    def level_max_length(cls, value):
        assert len(value) <= 256
        return value


EducationalResourceCreate.update_forward_refs()
