# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

from app.schemas.aiod_generated.aio_d_entry_create import AIoDEntryCreate


class EventCreate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EventCreate - a model defined in OpenAPI

        platform: The platform of this EventCreate [Optional].
        platform_identifier: The platform_identifier of this EventCreate [Optional].
        name: The name of this EventCreate.
        description: The description of this EventCreate [Optional].
        same_as: The same_as of this EventCreate [Optional].
        start_date: The start_date of this EventCreate [Optional].
        end_date: The end_date of this EventCreate [Optional].
        schedule: The schedule of this EventCreate [Optional].
        registration_link: The registration_link of this EventCreate [Optional].
        aiod_entry: The aiod_entry of this EventCreate [Optional].
        alternate_name: The alternate_name of this EventCreate [Optional].
        application_area: The application_area of this EventCreate [Optional].
        contact: The contact of this EventCreate [Optional].
        has_part: The has_part of this EventCreate [Optional].
        industrial_sector: The industrial_sector of this EventCreate [Optional].
        is_part_of: The is_part_of of this EventCreate [Optional].
        keyword: The keyword of this EventCreate [Optional].
        media: The media of this EventCreate [Optional].
        mode: The mode of this EventCreate [Optional].
        note: The note of this EventCreate [Optional].
        organiser: The organiser of this EventCreate [Optional].
        performer: The performer of this EventCreate [Optional].
        research_area: The research_area of this EventCreate [Optional].
        scientific_domain: The scientific_domain of this EventCreate [Optional].
        status: The status of this EventCreate [Optional].
    """

    platform: Optional[object] = Field(alias="platform", default=None)
    platform_identifier: Optional[object] = Field(
        alias="platform_identifier", default=None
    )
    name: object = Field(alias="name")
    description: Optional[object] = Field(alias="description", default=None)
    same_as: Optional[object] = Field(alias="same_as", default=None)
    start_date: Optional[object] = Field(alias="start_date", default=None)
    end_date: Optional[object] = Field(alias="end_date", default=None)
    schedule: Optional[object] = Field(alias="schedule", default=None)
    registration_link: Optional[object] = Field(alias="registration_link", default=None)
    aiod_entry: Optional[AIoDEntryCreate] = Field(alias="aiod_entry", default=None)
    alternate_name: Optional[object] = Field(alias="alternate_name", default=None)
    application_area: Optional[object] = Field(alias="application_area", default=None)
    contact: Optional[object] = Field(alias="contact", default=None)
    has_part: Optional[object] = Field(alias="has_part", default=None)
    industrial_sector: Optional[object] = Field(alias="industrial_sector", default=None)
    is_part_of: Optional[object] = Field(alias="is_part_of", default=None)
    keyword: Optional[object] = Field(alias="keyword", default=None)
    media: Optional[object] = Field(alias="media", default=None)
    mode: Optional[object] = Field(alias="mode", default=None)
    note: Optional[object] = Field(alias="note", default=None)
    organiser: Optional[object] = Field(alias="organiser", default=None)
    performer: Optional[object] = Field(alias="performer", default=None)
    research_area: Optional[object] = Field(alias="research_area", default=None)
    scientific_domain: Optional[object] = Field(alias="scientific_domain", default=None)
    status: Optional[object] = Field(alias="status", default=None)

    @validator("platform")
    def platform_max_length(cls, value):
        assert len(value) <= 64
        return value

    @validator("platform_identifier")
    def platform_identifier_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("name")
    def name_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("description")
    def description_max_length(cls, value):
        assert len(value) <= 1800
        return value

    @validator("same_as")
    def same_as_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("schedule")
    def schedule_max_length(cls, value):
        assert len(value) <= 1800
        return value

    @validator("registration_link")
    def registration_link_max_length(cls, value):
        assert len(value) <= 256
        return value


EventCreate.update_forward_refs()
