# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

from app.schemas.aiod_generated.aio_d_entry_read import AIoDEntryRead
from app.schemas.aiod_generated.distribution import Distribution


class EventRead(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EventRead - a model defined in OpenAPI

        platform: The platform of this EventRead [Optional].
        platform_identifier: The platform_identifier of this EventRead [Optional].
        name: The name of this EventRead.
        description: The description of this EventRead [Optional].
        same_as: The same_as of this EventRead [Optional].
        start_date: The start_date of this EventRead [Optional].
        end_date: The end_date of this EventRead [Optional].
        schedule: The schedule of this EventRead [Optional].
        registration_link: The registration_link of this EventRead [Optional].
        ai_resource_identifier: The ai_resource_identifier of this EventRead [Optional].
        aiod_entry: The aiod_entry of this EventRead [Optional].
        alternate_name: The alternate_name of this EventRead [Optional].
        application_area: The application_area of this EventRead [Optional].
        contact: The contact of this EventRead [Optional].
        has_part: The has_part of this EventRead [Optional].
        industrial_sector: The industrial_sector of this EventRead [Optional].
        is_part_of: The is_part_of of this EventRead [Optional].
        keyword: The keyword of this EventRead [Optional].
        media: The media of this EventRead [Optional].
        mode: The mode of this EventRead [Optional].
        note: The note of this EventRead [Optional].
        organiser: The organiser of this EventRead [Optional].
        performer: The performer of this EventRead [Optional].
        research_area: The research_area of this EventRead [Optional].
        scientific_domain: The scientific_domain of this EventRead [Optional].
        status: The status of this EventRead [Optional].
        identifier: The identifier of this EventRead.
    """

    platform: Optional[str] = Field(alias="platform", default=None)
    platform_identifier: Optional[str] = Field(
        alias="platform_identifier", default=None
    )
    name: str = Field(alias="name")
    description: Optional[str] = Field(alias="description", default=None)
    same_as: Optional[str] = Field(alias="same_as", default=None)
    start_date: Optional[datetime] = Field(alias="start_date", default=None)
    end_date: Optional[datetime] = Field(alias="end_date", default=None)
    schedule: Optional[str] = Field(alias="schedule", default=None)
    registration_link: Optional[str] = Field(alias="registration_link", default=None)
    ai_resource_identifier: Optional[int] = Field(
        alias="ai_resource_identifier", default=None
    )
    aiod_entry: Optional[AIoDEntryRead] = Field(alias="aiod_entry", default=None)
    alternate_name: Optional[List[str]] = Field(alias="alternate_name", default=None)
    application_area: Optional[List[str]] = Field(
        alias="application_area", default=None
    )
    contact: Optional[List[int]] = Field(alias="contact", default=None)
    has_part: Optional[List[int]] = Field(alias="has_part", default=None)
    industrial_sector: Optional[List[str]] = Field(
        alias="industrial_sector", default=None
    )
    is_part_of: Optional[List[int]] = Field(alias="is_part_of", default=None)
    keyword: Optional[List[str]] = Field(alias="keyword", default=None)
    media: Optional[List[Distribution]] = Field(alias="media", default=None)
    mode: Optional[str] = Field(alias="mode", default=None)
    note: Optional[List[str]] = Field(alias="note", default=None)
    organiser: Optional[int] = Field(alias="organiser", default=None)
    performer: Optional[List[int]] = Field(alias="performer", default=None)
    research_area: Optional[List[str]] = Field(alias="research_area", default=None)
    scientific_domain: Optional[List[str]] = Field(
        alias="scientific_domain", default=None
    )
    status: Optional[str] = Field(alias="status", default=None)
    identifier: int = Field(alias="identifier")

    @validator("platform")
    def platform_max_length(cls, value):
        assert len(value) <= 64
        return value

    @validator("platform_identifier")
    def platform_identifier_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("name")
    def name_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("description")
    def description_max_length(cls, value):
        assert len(value) <= 1800
        return value

    @validator("same_as")
    def same_as_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("schedule")
    def schedule_max_length(cls, value):
        assert len(value) <= 1800
        return value

    @validator("registration_link")
    def registration_link_max_length(cls, value):
        assert len(value) <= 256
        return value


EventRead.update_forward_refs()
