# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Geo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Geo - a model defined in OpenAPI

        latitude: The latitude of this Geo [Optional].
        longitude: The longitude of this Geo [Optional].
        elevation_millimeters: The elevation_millimeters of this Geo [Optional].
    """

    latitude: Optional[float] = Field(alias="latitude", default=None)
    longitude: Optional[float] = Field(alias="longitude", default=None)
    elevation_millimeters: Optional[int] = Field(
        alias="elevation_millimeters", default=None
    )


Geo.update_forward_refs()
