# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

from app.schemas.aiod_generated.dcat_ap_dataset import DcatAPDataset
from app.schemas.aiod_generated.dcat_ap_distribution import DcatAPDistribution
from app.schemas.aiod_generated.dcat_ap_identifier import DcatAPIdentifier
from app.schemas.aiod_generated.dcat_location import DcatLocation
from app.schemas.aiod_generated.dct_period_of_time import DctPeriodOfTime
from app.schemas.aiod_generated.spdx_checksum import SpdxChecksum
from app.schemas.aiod_generated.v_card_individual import VCardIndividual
from app.schemas.aiod_generated.v_card_organisation import VCardOrganisation
from app.schemas.aiod_generated.xsd_date_time import XSDDateTime


class GraphInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GraphInner - a model defined in OpenAPI

        id: The id of this GraphInner.
        type: The type of this GraphInner [Optional].
        dctdescription: The dctdescription of this GraphInner.
        dcttitle: The dcttitle of this GraphInner.
        dcatcontact_point: The dcatcontact_point of this GraphInner [Optional].
        dcatdistribution: The dcatdistribution of this GraphInner [Optional].
        dcatkeyword: The dcatkeyword of this GraphInner [Optional].
        dctpublisher: The dctpublisher of this GraphInner [Optional].
        dcatcreator: The dcatcreator of this GraphInner [Optional].
        foafpage: The foafpage of this GraphInner [Optional].
        dcatlanding_page: The dcatlanding_page of this GraphInner [Optional].
        dctissued: The dctissued of this GraphInner [Optional].
        dctmodified: The dctmodified of this GraphInner [Optional].
        owlversion_info: The owlversion_info of this GraphInner [Optional].
        dcataccess_url: The dcataccess_url of this GraphInner [Optional].
        dcatbyte_size: The dcatbyte_size of this GraphInner [Optional].
        spdxchecksum: The spdxchecksum of this GraphInner [Optional].
        dcatdownload_url: The dcatdownload_url of this GraphInner [Optional].
        dctformat: The dctformat of this GraphInner [Optional].
        dctlicense: The dctlicense of this GraphInner [Optional].
        dcatbbox: The dcatbbox of this GraphInner [Optional].
        dcatcentroid: The dcatcentroid of this GraphInner [Optional].
        dcatgeometry: The dcatgeometry of this GraphInner [Optional].
        algorithm: The algorithm of this GraphInner.
        checksum_value: The checksum_value of this GraphInner.
        vcardfn: The vcardfn of this GraphInner.
        dcatstart_date: The dcatstart_date of this GraphInner [Optional].
        dcatend_date: The dcatend_date of this GraphInner [Optional].
    """

    id: str = Field(alias="@id")
    type: Optional[str] = Field(alias="@type", default=None)
    dctdescription: str = Field(alias="dct:description")
    dcttitle: str = Field(alias="dct:title")
    dcatcontact_point: Optional[List[DcatAPIdentifier]] = Field(
        alias="dcat:contactPoint", default=None
    )
    dcatdistribution: Optional[List[DcatAPIdentifier]] = Field(
        alias="dcat:distribution", default=None
    )
    dcatkeyword: Optional[List[str]] = Field(alias="dcat:keyword", default=None)
    dctpublisher: Optional[DcatAPIdentifier] = Field(
        alias="dct:publisher", default=None
    )
    dcatcreator: Optional[List[DcatAPIdentifier]] = Field(
        alias="dcat:creator", default=None
    )
    foafpage: Optional[List[str]] = Field(alias="foaf:page", default=None)
    dcatlanding_page: Optional[List[str]] = Field(
        alias="dcat:landingPage", default=None
    )
    dctissued: Optional[XSDDateTime] = Field(alias="dct:issued", default=None)
    dctmodified: Optional[XSDDateTime] = Field(alias="dct:modified", default=None)
    owlversion_info: Optional[str] = Field(alias="owl:versionInfo", default=None)
    dcataccess_url: Optional[str] = Field(alias="dcat:accessURL", default=None)
    dcatbyte_size: Optional[int] = Field(alias="dcat:byteSize", default=None)
    spdxchecksum: Optional[DcatAPIdentifier] = Field(
        alias="spdx:checksum", default=None
    )
    dcatdownload_url: Optional[str] = Field(alias="dcat:downloadURL", default=None)
    dctformat: Optional[str] = Field(alias="dct:format", default=None)
    dctlicense: Optional[str] = Field(alias="dct:license", default=None)
    dcatbbox: Optional[str] = Field(alias="dcat:bbox", default=None)
    dcatcentroid: Optional[str] = Field(alias="dcat:centroid", default=None)
    dcatgeometry: Optional[str] = Field(alias="dcat:geometry", default=None)
    algorithm: str = Field(alias="algorithm")
    checksum_value: str = Field(alias="checksumValue")
    vcardfn: str = Field(alias="vcard:fn")
    dcatstart_date: Optional[XSDDateTime] = Field(alias="dcat:startDate", default=None)
    dcatend_date: Optional[XSDDateTime] = Field(alias="dcat:endDate", default=None)


GraphInner.update_forward_refs()
