# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class HTTPValidationError(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    HTTPValidationError - a model defined in OpenAPI

        detail: The detail of this HTTPValidationError [Optional].
    """

    detail: Optional[object] = Field(alias="detail", default=None)


HTTPValidationError.update_forward_refs()
