# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

from app.schemas.aiod_generated.address import Address
from app.schemas.aiod_generated.geo import Geo


class Location(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Location - a model defined in OpenAPI

        address: The address of this Location [Optional].
        geo: The geo of this Location [Optional].
    """

    address: Optional[Address] = Field(alias="address", default=None)
    geo: Optional[Geo] = Field(alias="geo", default=None)


Location.update_forward_refs()
