# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Maintainer(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Maintainer - a model defined in OpenAPI

        type: The type of this Maintainer [Optional].
        name: The name of this Maintainer.
    """

    type: Optional[str] = Field(alias="@type", default=None)
    name: str = Field(alias="name")

Maintainer.update_forward_refs()
