# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class MeasuredValue(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MeasuredValue - a model defined in OpenAPI

        variable: The variable of this MeasuredValue.
        technique: The technique of this MeasuredValue.
    """

    variable: str = Field(alias="variable")
    technique: str = Field(alias="technique")

    @validator("variable")
    def variable_max_length(cls, value):
        assert len(value) <= 150
        return value

    @validator("technique")
    def technique_max_length(cls, value):
        assert len(value) <= 150
        return value

MeasuredValue.update_forward_refs()
