# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

from app.schemas.aiod_generated.aio_d_entry_create import AIoDEntryCreate
from app.schemas.aiod_generated.distribution import Distribution


class ProjectCreate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ProjectCreate - a model defined in OpenAPI

        platform: The platform of this ProjectCreate [Optional].
        platform_identifier: The platform_identifier of this ProjectCreate [Optional].
        name: The name of this ProjectCreate.
        description: The description of this ProjectCreate [Optional].
        same_as: The same_as of this ProjectCreate [Optional].
        start_date: The start_date of this ProjectCreate [Optional].
        end_date: The end_date of this ProjectCreate [Optional].
        total_cost_euro: The total_cost_euro of this ProjectCreate [Optional].
        aiod_entry: The aiod_entry of this ProjectCreate [Optional].
        alternate_name: The alternate_name of this ProjectCreate [Optional].
        application_area: The application_area of this ProjectCreate [Optional].
        contact: The contact of this ProjectCreate [Optional].
        coordinator: The coordinator of this ProjectCreate [Optional].
        funder: The funder of this ProjectCreate [Optional].
        has_part: The has_part of this ProjectCreate [Optional].
        industrial_sector: The industrial_sector of this ProjectCreate [Optional].
        is_part_of: The is_part_of of this ProjectCreate [Optional].
        keyword: The keyword of this ProjectCreate [Optional].
        media: The media of this ProjectCreate [Optional].
        note: The note of this ProjectCreate [Optional].
        participant: The participant of this ProjectCreate [Optional].
        produced: The produced of this ProjectCreate [Optional].
        research_area: The research_area of this ProjectCreate [Optional].
        scientific_domain: The scientific_domain of this ProjectCreate [Optional].
        used: The used of this ProjectCreate [Optional].
    """

    platform: Optional[str] = Field(alias="platform", default=None)
    platform_identifier: Optional[str] = Field(
        alias="platform_identifier", default=None
    )
    name: str = Field(alias="name")
    description: Optional[str] = Field(alias="description", default=None)
    same_as: Optional[str] = Field(alias="same_as", default=None)
    start_date: Optional[datetime] = Field(alias="start_date", default=None)
    end_date: Optional[datetime] = Field(alias="end_date", default=None)
    total_cost_euro: Optional[float] = Field(alias="total_cost_euro", default=None)
    aiod_entry: Optional[AIoDEntryCreate] = Field(alias="aiod_entry", default=None)
    alternate_name: Optional[List[str]] = Field(alias="alternate_name", default=None)
    application_area: Optional[List[str]] = Field(
        alias="application_area", default=None
    )
    contact: Optional[List[int]] = Field(alias="contact", default=None)
    coordinator: Optional[int] = Field(alias="coordinator", default=None)
    funder: Optional[List[int]] = Field(alias="funder", default=None)
    has_part: Optional[List[int]] = Field(alias="has_part", default=None)
    industrial_sector: Optional[List[str]] = Field(
        alias="industrial_sector", default=None
    )
    is_part_of: Optional[List[int]] = Field(alias="is_part_of", default=None)
    keyword: Optional[List[str]] = Field(alias="keyword", default=None)
    media: Optional[List[Distribution]] = Field(alias="media", default=None)
    note: Optional[List[str]] = Field(alias="note", default=None)
    participant: Optional[List[int]] = Field(alias="participant", default=None)
    produced: Optional[List[int]] = Field(alias="produced", default=None)
    research_area: Optional[List[str]] = Field(alias="research_area", default=None)
    scientific_domain: Optional[List[str]] = Field(
        alias="scientific_domain", default=None
    )
    used: Optional[List[int]] = Field(alias="used", default=None)

    @validator("platform")
    def platform_max_length(cls, value):
        assert len(value) <= 64
        return value

    @validator("platform_identifier")
    def platform_identifier_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("name")
    def name_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("description")
    def description_max_length(cls, value):
        assert len(value) <= 1800
        return value

    @validator("same_as")
    def same_as_max_length(cls, value):
        assert len(value) <= 256
        return value


ProjectCreate.update_forward_refs()
