# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

from app.schemas.aiod_generated.aio_d_entry_read import AIoDEntryRead
from app.schemas.aiod_generated.distribution import Distribution
from app.schemas.aiod_generated.organisation_read import OrganisationRead
from app.schemas.aiod_generated.person_read import PersonRead


class ResponseAgentAgentsV1IdentifierGet(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ResponseAgentAgentsV1IdentifierGet - a model defined in OpenAPI

        platform: The platform of this ResponseAgentAgentsV1IdentifierGet [Optional].
        platform_identifier: The platform_identifier of this ResponseAgentAgentsV1IdentifierGet [Optional].
        name: The name of this ResponseAgentAgentsV1IdentifierGet.
        description: The description of this ResponseAgentAgentsV1IdentifierGet [Optional].
        same_as: The same_as of this ResponseAgentAgentsV1IdentifierGet [Optional].
        date_founded: The date_founded of this ResponseAgentAgentsV1IdentifierGet [Optional].
        legal_name: The legal_name of this ResponseAgentAgentsV1IdentifierGet [Optional].
        ai_relevance: The ai_relevance of this ResponseAgentAgentsV1IdentifierGet [Optional].
        agent_identifier: The agent_identifier of this ResponseAgentAgentsV1IdentifierGet [Optional].
        ai_resource_identifier: The ai_resource_identifier of this ResponseAgentAgentsV1IdentifierGet [Optional].
        aiod_entry: The aiod_entry of this ResponseAgentAgentsV1IdentifierGet [Optional].
        alternate_name: The alternate_name of this ResponseAgentAgentsV1IdentifierGet [Optional].
        application_area: The application_area of this ResponseAgentAgentsV1IdentifierGet [Optional].
        contact: The contact of this ResponseAgentAgentsV1IdentifierGet [Optional].
        email: The email of this ResponseAgentAgentsV1IdentifierGet [Optional].
        has_part: The has_part of this ResponseAgentAgentsV1IdentifierGet [Optional].
        industrial_sector: The industrial_sector of this ResponseAgentAgentsV1IdentifierGet [Optional].
        is_part_of: The is_part_of of this ResponseAgentAgentsV1IdentifierGet [Optional].
        keyword: The keyword of this ResponseAgentAgentsV1IdentifierGet [Optional].
        media: The media of this ResponseAgentAgentsV1IdentifierGet [Optional].
        member: The member of this ResponseAgentAgentsV1IdentifierGet [Optional].
        note: The note of this ResponseAgentAgentsV1IdentifierGet [Optional].
        research_area: The research_area of this ResponseAgentAgentsV1IdentifierGet [Optional].
        scientific_domain: The scientific_domain of this ResponseAgentAgentsV1IdentifierGet [Optional].
        telephone: The telephone of this ResponseAgentAgentsV1IdentifierGet [Optional].
        type: The type of this ResponseAgentAgentsV1IdentifierGet [Optional].
        identifier: The identifier of this ResponseAgentAgentsV1IdentifierGet.
        given_name: The given_name of this ResponseAgentAgentsV1IdentifierGet [Optional].
        surname: The surname of this ResponseAgentAgentsV1IdentifierGet [Optional].
        price_per_hour_euro: The price_per_hour_euro of this ResponseAgentAgentsV1IdentifierGet [Optional].
        wants_to_be_contacted: The wants_to_be_contacted of this ResponseAgentAgentsV1IdentifierGet [Optional].
        expertise: The expertise of this ResponseAgentAgentsV1IdentifierGet [Optional].
        language: The language of this ResponseAgentAgentsV1IdentifierGet [Optional].
    """

    platform: Optional[str] = Field(alias="platform", default=None)
    platform_identifier: Optional[str] = Field(
        alias="platform_identifier", default=None
    )
    name: str = Field(alias="name")
    description: Optional[str] = Field(alias="description", default=None)
    same_as: Optional[str] = Field(alias="same_as", default=None)
    date_founded: Optional[date] = Field(alias="date_founded", default=None)
    legal_name: Optional[str] = Field(alias="legal_name", default=None)
    ai_relevance: Optional[str] = Field(alias="ai_relevance", default=None)
    agent_identifier: Optional[int] = Field(alias="agent_identifier", default=None)
    ai_resource_identifier: Optional[int] = Field(
        alias="ai_resource_identifier", default=None
    )
    aiod_entry: Optional[AIoDEntryRead] = Field(alias="aiod_entry", default=None)
    alternate_name: Optional[List[str]] = Field(alias="alternate_name", default=None)
    application_area: Optional[List[str]] = Field(
        alias="application_area", default=None
    )
    contact: Optional[List[int]] = Field(alias="contact", default=None)
    email: Optional[List[str]] = Field(alias="email", default=None)
    has_part: Optional[List[int]] = Field(alias="has_part", default=None)
    industrial_sector: Optional[List[str]] = Field(
        alias="industrial_sector", default=None
    )
    is_part_of: Optional[List[int]] = Field(alias="is_part_of", default=None)
    keyword: Optional[List[str]] = Field(alias="keyword", default=None)
    media: Optional[List[Distribution]] = Field(alias="media", default=None)
    member: Optional[List[int]] = Field(alias="member", default=None)
    note: Optional[List[str]] = Field(alias="note", default=None)
    research_area: Optional[List[str]] = Field(alias="research_area", default=None)
    scientific_domain: Optional[List[str]] = Field(
        alias="scientific_domain", default=None
    )
    telephone: Optional[List[str]] = Field(alias="telephone", default=None)
    type: Optional[str] = Field(alias="type", default=None)
    identifier: int = Field(alias="identifier")
    given_name: Optional[str] = Field(alias="given_name", default=None)
    surname: Optional[str] = Field(alias="surname", default=None)
    price_per_hour_euro: Optional[float] = Field(
        alias="price_per_hour_euro", default=None
    )
    wants_to_be_contacted: Optional[bool] = Field(
        alias="wants_to_be_contacted", default=None
    )
    expertise: Optional[List[str]] = Field(alias="expertise", default=None)
    language: Optional[List[str]] = Field(alias="language", default=None)

    @validator("platform")
    def platform_max_length(cls, value):
        assert len(value) <= 64
        return value

    @validator("platform_identifier")
    def platform_identifier_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("name")
    def name_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("description")
    def description_max_length(cls, value):
        assert len(value) <= 1800
        return value

    @validator("same_as")
    def same_as_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("legal_name")
    def legal_name_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("ai_relevance")
    def ai_relevance_max_length(cls, value):
        assert len(value) <= 1800
        return value

    @validator("given_name")
    def given_name_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("surname")
    def surname_max_length(cls, value):
        assert len(value) <= 256
        return value


ResponseAgentAgentsV1IdentifierGet.update_forward_refs()
