# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

from app.schemas.aiod_generated.aio_d_entry_read import AIoDEntryRead
from app.schemas.aiod_generated.case_study_read import CaseStudyRead
from app.schemas.aiod_generated.computational_asset_read import ComputationalAssetRead
from app.schemas.aiod_generated.dataset_read import DatasetRead
from app.schemas.aiod_generated.distribution import Distribution
from app.schemas.aiod_generated.educational_resource_read import EducationalResourceRead
from app.schemas.aiod_generated.event_read import EventRead
from app.schemas.aiod_generated.experiment_read import ExperimentRead
from app.schemas.aiod_generated.location import Location
from app.schemas.aiod_generated.ml_model_read import MLModelRead
from app.schemas.aiod_generated.news_read import NewsRead
from app.schemas.aiod_generated.organisation_read import OrganisationRead
from app.schemas.aiod_generated.person_read import PersonRead
from app.schemas.aiod_generated.project_read import ProjectRead
from app.schemas.aiod_generated.publication_read import PublicationRead
from app.schemas.aiod_generated.runnable_distribution import RunnableDistribution
from app.schemas.aiod_generated.service_read import ServiceRead
from app.schemas.aiod_generated.team_read import TeamRead


class ResponseAiResourceAiResourcesV1IdentifierGet(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ResponseAiResourceAiResourcesV1IdentifierGet - a model defined in OpenAPI

        platform: The platform of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        platform_identifier: The platform_identifier of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        name: The name of this ResponseAiResourceAiResourcesV1IdentifierGet.
        description: The description of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        same_as: The same_as of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        date_founded: The date_founded of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        legal_name: The legal_name of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        ai_relevance: The ai_relevance of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        agent_identifier: The agent_identifier of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        ai_resource_identifier: The ai_resource_identifier of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        aiod_entry: The aiod_entry of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        alternate_name: The alternate_name of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        application_area: The application_area of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        contact: The contact of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        email: The email of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        has_part: The has_part of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        industrial_sector: The industrial_sector of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        is_part_of: The is_part_of of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        keyword: The keyword of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        media: The media of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        member: The member of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        note: The note of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        research_area: The research_area of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        scientific_domain: The scientific_domain of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        telephone: The telephone of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        type: The type of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        identifier: The identifier of this ResponseAiResourceAiResourcesV1IdentifierGet.
        given_name: The given_name of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        surname: The surname of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        price_per_hour_euro: The price_per_hour_euro of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        wants_to_be_contacted: The wants_to_be_contacted of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        expertise: The expertise of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        language: The language of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        date_published: The date_published of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        is_accessible_for_free: The is_accessible_for_free of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        version: The version of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        issn: The issn of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        measurement_technique: The measurement_technique of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        temporal_coverage: The temporal_coverage of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        ai_asset_identifier: The ai_asset_identifier of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        citation: The citation of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        creator: The creator of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        distribution: The distribution of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        funder: The funder of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        license: The license of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        size: The size of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        spatial_coverage: The spatial_coverage of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        permanent_identifier: The permanent_identifier of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        isbn: The isbn of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        documents: The documents of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        status_info: The status_info of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        pid: The pid of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        experimental_workflow: The experimental_workflow of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        execution_settings: The execution_settings of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        reproducibility_explanation: The reproducibility_explanation of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        badge: The badge of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        related_experiment: The related_experiment of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        level: The level of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        start_date: The start_date of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        end_date: The end_date of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        schedule: The schedule of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        registration_link: The registration_link of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        mode: The mode of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        organiser: The organiser of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        performer: The performer of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        status: The status of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        headline: The headline of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        alternative_headline: The alternative_headline of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        total_cost_euro: The total_cost_euro of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        coordinator: The coordinator of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        participant: The participant of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        produced: The produced of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        used: The used of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        slogan: The slogan of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        terms_of_service: The terms_of_service of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
        organisation: The organisation of this ResponseAiResourceAiResourcesV1IdentifierGet [Optional].
    """

    platform: Optional[str] = Field(alias="platform", default=None)
    platform_identifier: Optional[str] = Field(
        alias="platform_identifier", default=None
    )
    name: str = Field(alias="name")
    description: Optional[str] = Field(alias="description", default=None)
    same_as: Optional[str] = Field(alias="same_as", default=None)
    date_founded: Optional[date] = Field(alias="date_founded", default=None)
    legal_name: Optional[str] = Field(alias="legal_name", default=None)
    ai_relevance: Optional[str] = Field(alias="ai_relevance", default=None)
    agent_identifier: Optional[int] = Field(alias="agent_identifier", default=None)
    ai_resource_identifier: Optional[int] = Field(
        alias="ai_resource_identifier", default=None
    )
    aiod_entry: Optional[AIoDEntryRead] = Field(alias="aiod_entry", default=None)
    alternate_name: Optional[List[str]] = Field(alias="alternate_name", default=None)
    application_area: Optional[List[str]] = Field(
        alias="application_area", default=None
    )
    contact: Optional[List[int]] = Field(alias="contact", default=None)
    email: Optional[List[str]] = Field(alias="email", default=None)
    has_part: Optional[List[int]] = Field(alias="has_part", default=None)
    industrial_sector: Optional[List[str]] = Field(
        alias="industrial_sector", default=None
    )
    is_part_of: Optional[List[int]] = Field(alias="is_part_of", default=None)
    keyword: Optional[List[str]] = Field(alias="keyword", default=None)
    media: Optional[List[Distribution]] = Field(alias="media", default=None)
    member: Optional[List[int]] = Field(alias="member", default=None)
    note: Optional[List[str]] = Field(alias="note", default=None)
    research_area: Optional[List[str]] = Field(alias="research_area", default=None)
    scientific_domain: Optional[List[str]] = Field(
        alias="scientific_domain", default=None
    )
    telephone: Optional[List[str]] = Field(alias="telephone", default=None)
    type: Optional[str] = Field(alias="type", default=None)
    identifier: int = Field(alias="identifier")
    given_name: Optional[str] = Field(alias="given_name", default=None)
    surname: Optional[str] = Field(alias="surname", default=None)
    price_per_hour_euro: Optional[float] = Field(
        alias="price_per_hour_euro", default=None
    )
    wants_to_be_contacted: Optional[bool] = Field(
        alias="wants_to_be_contacted", default=None
    )
    expertise: Optional[List[str]] = Field(alias="expertise", default=None)
    language: Optional[List[str]] = Field(alias="language", default=None)
    date_published: Optional[datetime] = Field(alias="date_published", default=None)
    is_accessible_for_free: Optional[bool] = Field(
        alias="is_accessible_for_free", default=None
    )
    version: Optional[str] = Field(alias="version", default=None)
    issn: Optional[str] = Field(alias="issn", default=None)
    measurement_technique: Optional[str] = Field(
        alias="measurement_technique", default=None
    )
    temporal_coverage: Optional[str] = Field(alias="temporal_coverage", default=None)
    ai_asset_identifier: Optional[int] = Field(
        alias="ai_asset_identifier", default=None
    )
    citation: Optional[List[int]] = Field(alias="citation", default=None)
    creator: Optional[List[int]] = Field(alias="creator", default=None)
    distribution: Optional[List[RunnableDistribution]] = Field(
        alias="distribution", default=None
    )
    funder: Optional[List[int]] = Field(alias="funder", default=None)
    license: Optional[str] = Field(alias="license", default=None)
    size: Optional[int] = Field(alias="size", default=None)
    spatial_coverage: Optional[Location] = Field(alias="spatial_coverage", default=None)
    permanent_identifier: Optional[str] = Field(
        alias="permanent_identifier", default=None
    )
    isbn: Optional[str] = Field(alias="isbn", default=None)
    documents: Optional[List[int]] = Field(alias="documents", default=None)
    status_info: Optional[str] = Field(alias="status_info", default=None)
    pid: Optional[str] = Field(alias="pid", default=None)
    experimental_workflow: Optional[str] = Field(
        alias="experimental_workflow", default=None
    )
    execution_settings: Optional[str] = Field(alias="execution_settings", default=None)
    reproducibility_explanation: Optional[str] = Field(
        alias="reproducibility_explanation", default=None
    )
    badge: Optional[List[str]] = Field(alias="badge", default=None)
    related_experiment: Optional[List[int]] = Field(
        alias="related_experiment", default=None
    )
    level: Optional[str] = Field(alias="level", default=None)
    start_date: Optional[datetime] = Field(alias="start_date", default=None)
    end_date: Optional[datetime] = Field(alias="end_date", default=None)
    schedule: Optional[str] = Field(alias="schedule", default=None)
    registration_link: Optional[str] = Field(alias="registration_link", default=None)
    mode: Optional[str] = Field(alias="mode", default=None)
    organiser: Optional[int] = Field(alias="organiser", default=None)
    performer: Optional[List[int]] = Field(alias="performer", default=None)
    status: Optional[str] = Field(alias="status", default=None)
    headline: Optional[str] = Field(alias="headline", default=None)
    alternative_headline: Optional[str] = Field(
        alias="alternative_headline", default=None
    )
    total_cost_euro: Optional[float] = Field(alias="total_cost_euro", default=None)
    coordinator: Optional[int] = Field(alias="coordinator", default=None)
    participant: Optional[List[int]] = Field(alias="participant", default=None)
    produced: Optional[List[int]] = Field(alias="produced", default=None)
    used: Optional[List[int]] = Field(alias="used", default=None)
    slogan: Optional[str] = Field(alias="slogan", default=None)
    terms_of_service: Optional[str] = Field(alias="terms_of_service", default=None)
    organisation: Optional[int] = Field(alias="organisation", default=None)

    @validator("platform")
    def platform_max_length(cls, value):
        assert len(value) <= 64
        return value

    @validator("platform_identifier")
    def platform_identifier_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("name")
    def name_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("description")
    def description_max_length(cls, value):
        assert len(value) <= 1800
        return value

    @validator("same_as")
    def same_as_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("legal_name")
    def legal_name_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("ai_relevance")
    def ai_relevance_max_length(cls, value):
        assert len(value) <= 1800
        return value

    @validator("given_name")
    def given_name_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("surname")
    def surname_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("version")
    def version_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("issn")
    def issn_min_length(cls, value):
        assert len(value) >= 8
        return value

    @validator("issn")
    def issn_max_length(cls, value):
        assert len(value) <= 8
        return value

    @validator("measurement_technique")
    def measurement_technique_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("temporal_coverage")
    def temporal_coverage_max_length(cls, value):
        assert len(value) <= 64
        return value

    @validator("permanent_identifier")
    def permanent_identifier_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("isbn")
    def isbn_min_length(cls, value):
        assert len(value) >= 10
        return value

    @validator("isbn")
    def isbn_max_length(cls, value):
        assert len(value) <= 13
        return value

    @validator("status_info")
    def status_info_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("pid")
    def pid_max_length(cls, value):
        assert len(value) <= 64
        return value

    @validator("experimental_workflow")
    def experimental_workflow_max_length(cls, value):
        assert len(value) <= 1800
        return value

    @validator("execution_settings")
    def execution_settings_max_length(cls, value):
        assert len(value) <= 1800
        return value

    @validator("reproducibility_explanation")
    def reproducibility_explanation_max_length(cls, value):
        assert len(value) <= 1800
        return value

    @validator("level")
    def level_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("schedule")
    def schedule_max_length(cls, value):
        assert len(value) <= 1800
        return value

    @validator("registration_link")
    def registration_link_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("headline")
    def headline_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("alternative_headline")
    def alternative_headline_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("slogan")
    def slogan_max_length(cls, value):
        assert len(value) <= 256
        return value

    @validator("terms_of_service")
    def terms_of_service_max_length(cls, value):
        assert len(value) <= 1800
        return value


ResponseAiResourceAiResourcesV1IdentifierGet.update_forward_refs()
