# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class SchemaDotOrgDataDownload(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SchemaDotOrgDataDownload - a model defined in OpenAPI

        type: The type of this SchemaDotOrgDataDownload [Optional].
        name: The name of this SchemaDotOrgDataDownload [Optional].
        content_url: The content_url of this SchemaDotOrgDataDownload.
        content_size: The content_size of this SchemaDotOrgDataDownload [Optional].
        encoding_format: The encoding_format of this SchemaDotOrgDataDownload [Optional].
    """

    type: Optional[object] = Field(alias="@type", default=None)
    name: Optional[object] = Field(alias="name", default=None)
    content_url: object = Field(alias="contentUrl")
    content_size: Optional[object] = Field(alias="contentSize", default=None)
    encoding_format: Optional[object] = Field(alias="encodingFormat", default=None)


SchemaDotOrgDataDownload.update_forward_refs()
