# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class SchemaDotOrgContext(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SchemaDotOrgContext - a model defined in OpenAPI

        vocab: The vocab of this SchemaDotOrgContext [Optional].
    """

    vocab: Optional[str] = Field(alias="@vocab", default=None)


SchemaDotOrgContext.update_forward_refs()
