# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class SchemaDotOrgPerson(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SchemaDotOrgPerson - a model defined in OpenAPI

        type: The type of this SchemaDotOrgPerson [Optional].
        name: The name of this SchemaDotOrgPerson.
    """

    type: Optional[str] = Field(alias="@type", default=None)
    name: str = Field(alias="name")


SchemaDotOrgPerson.update_forward_refs()
