# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class SchemaDotOrgPerson(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SchemaDotOrgPerson - a model defined in OpenAPI

        type: The type of this SchemaDotOrgPerson [Optional].
        name: The name of this SchemaDotOrgPerson.
        given_name: The given_name of this SchemaDotOrgPerson [Optional].
        family_name: The family_name of this SchemaDotOrgPerson [Optional].
    """

    type: Optional[str] = Field(alias="@type", default=None)
    name: str = Field(alias="name")
    given_name: Optional[str] = Field(alias="givenName", default=None)
    family_name: Optional[str] = Field(alias="familyName", default=None)


SchemaDotOrgPerson.update_forward_refs()
