# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Size(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Size - a model defined in OpenAPI

        unit: The unit of this Size [Optional].
        value: The value of this Size [Optional].
    """

    unit: Optional[object] = Field(alias="unit", default=None)
    value: Optional[object] = Field(alias="value", default=None)

    @validator("unit")
    def unit_max_length(cls, value):
        assert len(value) <= 64
        return value


Size.update_forward_refs()
