# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class SpdxChecksum(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SpdxChecksum - a model defined in OpenAPI

        id: The id of this SpdxChecksum.
        type: The type of this SpdxChecksum [Optional].
        algorithm: The algorithm of this SpdxChecksum.
        checksum_value: The checksum_value of this SpdxChecksum.
    """

    id: str = Field(alias="@id")
    type: Optional[str] = Field(alias="@type", default=None)
    algorithm: str = Field(alias="algorithm")
    checksum_value: str = Field(alias="checksumValue")

SpdxChecksum.update_forward_refs()
