# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class VCardIndividual(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    VCardIndividual - a model defined in OpenAPI

        id: The id of this VCardIndividual.
        type: The type of this VCardIndividual [Optional].
        vcardfn: The vcardfn of this VCardIndividual.
    """

    id: object = Field(alias="@id")
    type: Optional[object] = Field(alias="@type", default=None)
    vcardfn: object = Field(alias="vcard:fn")


VCardIndividual.update_forward_refs()
