# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class VCardOrganisation(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    VCardOrganisation - a model defined in OpenAPI

        id: The id of this VCardOrganisation.
        type: The type of this VCardOrganisation [Optional].
        vcardfn: The vcardfn of this VCardOrganisation.
    """

    id: str = Field(alias="@id")
    type: Optional[str] = Field(alias="@type", default=None)
    vcardfn: str = Field(alias="vcard:fn")

VCardOrganisation.update_forward_refs()
