# coding: utf-8

from __future__ import annotations

import re  # noqa: F401
from datetime import date, datetime  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

from app.schemas.aiod_generated.value import Value


class XSDDateTime(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    XSDDateTime - a model defined in OpenAPI

        type: The type of this XSDDateTime [Optional].
        value: The value of this XSDDateTime.
    """

    type: Optional[str] = Field(alias="@type", default=None)
    value: Value = Field(alias="@value")


XSDDateTime.update_forward_refs()
