services:
  nginx:
    image: nginx:latest
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - frontend-app
      - backend-app
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    networks:
      - app

  # FRONTEND
  frontend-app:
    build:
      context: ./frontend-v2
      args:
        # One of local/dev/prod
        PROFILE: prod
    depends_on:
      - backend-app
    restart: always
    ports:
      - "5000:80"
    networks:
      - app

  # BACKEND
  backend-app:
    build:
      context: ./backend
    environment:
      - MONGODB_URI=mongodb://backend-db:27017
      - DOCKER_BASE_URL=unix:///var/run/docker.sock
      - EEE_DATA_PATH=/data/eee
    env_file:
      - ./backend/.env
    ports:
      - "8000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - eee_data:/data/eee
    command: >
      --port 80
      --root-path /api
    depends_on:
      backend-db:
        condition: service_started
    restart: always
    networks:
      - app
      - backend

  backend-db:
    image: mongo:6.0.6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - backend_db_data:/data/db
    networks:
      - backend

volumes:
  backend_db_data:
  eee_data:

networks:
  app:
    driver: bridge
  backend:
    driver: bridge
