services:
  app:
    build: .
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DOCKER_BASE_URL=unix:///var/run/docker.sock
      - EEE_DATA_PATH=/data/eee
    ports:
      - "8000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - eee_data:/data/eee
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0.6
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

volumes:
  db_data:
  eee_data:
