/**
 * AIoD - RAIL
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Address {
    /**
     * A subdivision of the country. Not necessary for most countries.
     */
    region?: string;
    /**
     * A city, town or village.
     */
    locality?: string;
    /**
     * The street address.
     */
    street?: string;
    /**
     * The postal code.
     */
    postal_code?: string;
    /**
     * Free text, in case the separate parts such as the street, postal code and country cannot be confidently separated.
     */
    address?: string;
    /**
     * The country as ISO 3166-1 alpha-3
     */
    country?: string;
}
