/**
 * AIOD - Practitioner\'s Portal
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type AssetCardinality = '0-N' | '1-N' | '1-1';

export const AssetCardinality = {
    _0N: '0-N' as AssetCardinality,
    _1N: '1-N' as AssetCardinality,
    _11: '1-1' as AssetCardinality
};

