/**
 * AIoD - RAIL
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssetCardinality } from './asset-cardinality';


export interface AssetSchema { 
    cardinality: AssetCardinality;
}
export namespace AssetSchema {
}


