/**
 * AIoD - RAIL
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Distribution {
    /**
     * The platform from which this resource originates. Defaults to `aiod` for assets registered directly on AI-on-Demand. This field should only be set by connectors, leave empty for users submitting assets. If platform is not None, `platform_resource_identifier` should also be set.
     */
    platform?: string;
    /**
     * The identifier by which the external platform (from `platform`) identifies the asset. Defaults to the asset identifier for assets registered directly on AIoD. This field should only be set by connectors, leave empty for users submitting assets.
     */
    platform_resource_identifier?: string;
    /**
     * The value of a checksum algorithm ran on this content.
     */
    checksum?: string;
    /**
     * The checksum algorithm.
     */
    checksum_algorithm?: string;
    copyright?: string;
    content_url?: string;
    content_size_kb?: number;
    /**
     * The datetime (utc) on which this Distribution was first published on an external platform.
     */
    date_published?: string;
    description?: string;
    /**
     * The mimetype of this file.
     */
    encoding_format?: string;
    name?: string;
    /**
     * The technology readiness level (TRL) of the distribution. TRL 1 is the lowest and stands for \'Basic principles observed\', TRL 9 is the highest and stands for \'actual system proven in operational environment\'.
     */
    technology_readiness_level?: number;
    /**
     * Binary blob for storing image (or other type of media) data. You may not set this property directly, set it indirectly through dedicated endpoints such as /organisations/{identifier}/image instead.
     */
    binary_blob?: Blob;
}
