/**
 * AIoD - RAIL
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export const EntryStatus = {
    Draft: 'draft',
    Published: 'published',
    Rejected: 'rejected',
    Submitted: 'submitted'
} as const;
export type EntryStatus = typeof EntryStatus[keyof typeof EntryStatus];

