/**
 * AIoD - RAIL
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EnvironmentVar {
<<<<<<< HEAD
    key: string;
    value: string;
=======
  key: string;
  value: string;
  is_secret: boolean;
>>>>>>> develop
}
