/**
 * AIoD - RAIL
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Platform { 
    /**
     * The name of the platform, such as huggingface, openml or zenodo. Preferably using snake_case.
     */
    name: string;
    identifier: string;
}

