/**
 * AIoD - RAIL
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Distribution } from './distribution';
import { Note } from './note';
import { Text } from './text';
import { AIoDEntryRead } from './aio-d-entry-read';
import { ContactRead } from './contact-read';


export interface Publication { 
    /**
     * The platform from which this resource originates. Defaults to `aiod` for assets registered directly on AI-on-Demand. This field should only be set by connectors, leave empty for users submitting assets. If platform is not None, `platform_resource_identifier` should also be set.
     */
    platform?: string;
    /**
     * The identifier by which the external platform (from `platform`) identifies the asset. Defaults to the asset identifier for assets registered directly on AIoD. This field should only be set by connectors, leave empty for users submitting assets. 
     */
    platform_resource_identifier?: string;
    name: string;
    /**
     * The datetime (utc) on which this resource was first published on an external platform. Note the difference between `.aiod_entry.date_created` and `.date_published`: the former is automatically set to the datetime the resource was created on AIoD, while the latter can optionally be set to an earlier datetime that the resource was published on an external platform.
     */
    date_published?: string;
    /**
     * Url of a reference Web page that unambiguously indicates this resource\'s identity.
     */
    same_as?: string;
    /**
     * A flag to signal that this asset is accessible at no cost.
     */
    is_accessible_for_free?: boolean;
    /**
     * The version of this asset.
     */
    version?: string;
    /**
     * A Permanent Identifier (e.g. DOI) for the entity
     */
    permanent_identifier?: string;
    /**
     * The International Standard Book Number, ISBN, used to identify published books or, more rarely, journal issues.
     */
    isbn?: string;
    /**
     * The International Standard Serial Number, ISSN, an identifier for serial publications.
     */
    issn?: string;
    ai_asset_identifier?: string;
    /**
     * This resource can be identified by its own identifier, but also by the resource_identifier.
     */
    ai_resource_identifier?: string;
    aiod_entry?: AIoDEntryRead;
    /**
     * An alias for the item, commonly used for the resource instead of the name.
     */
    alternate_name?: Array<string>;
    /**
     * The objective of this AI resource.
     */
    application_area?: Array<string>;
    /**
     * Publication identifiers that are a bibliographic reference.
     */
    citation?: Array<string>;
    /**
     * The identifiers of the contact information of the persons and/or organisations that can be contacted about this resource.
     */
    contact?: Array<string>;
    /**
     * Contact information corresponding to the identifiers found in `contact`.
     */
    contacts?: Array<ContactRead>;
    content?: Text;
    /**
     * The identifiers of the contact information of the persons and/or organisations that created this resource.
     */
    creator?: Array<string>;
    description?: Text;
    distribution?: Array<Distribution>;
    /**
     * The identifier of an AI asset for which the Knowledge Asset acts as an information source
     */
    documents?: Array<string>;
    has_part?: Array<string>;
    /**
     * A business domain where a resource is or can be used,see <a href=\"https://api.aiod.eu/docs#/Taxonomies/industrial_sector_industrial_sectors_get\">Industrial Sector</a> for more information.
     */
    industrial_sector?: Array<string>;
    is_part_of?: Array<string>;
    /**
     * Keywords or tags used to describe this resource, providing additional context.
     */
    keyword?: Array<string>;
    knowledge_asset_identifier?: string;
    license?: string;
    /**
     * Images or videos depicting the resource or associated with it. 
     */
    media?: Array<Distribution>;
    /**
     * Notes on this AI resource.
     */
    note?: Array<Note>;
    /**
     * URLs of relevant resources. These resources should not be part of AIoD (use relevant_resource otherwise). This field should only be used if there is no more specific field.
     */
    relevant_link?: Array<string>;
    relevant_resource?: Array<string>;
    relevant_to?: Array<string>;
    /**
     * Research Areas related to the asset. See <a href=\"https://api.aiod.eu/docs#/Taxonomies/research_area_research_areas_get\">Research Areas</a> for more information.
     */
    research_area?: Array<string>;
    /**
     * The methods with which an objective is reached. See <a href=\"https://api.aiod.eu/docs#/Taxonomies/scientific_domain_scientific_domains_get\">Scientific Domains</a> for more information.
     */
    scientific_domain?: Array<string>;
    /**
     * The type of publication.
     */
    type?: string;
    /**
     * AIoD Asset ID. Must be a 3 or 4 letter code followed by a 24 character random case-sensitive alphanumeric sequence
     */
    identifier: string;
}

