/**
 * AIOD - Practitioner\'s Portal
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type RunState = 'CREATED' | 'IN_PROGRESS' | 'CRASHED' | 'FINISHED';

export const RunState = {
    Created: 'CREATED' as RunState,
    InProgress: 'IN_PROGRESS' as RunState,
    Crashed: 'CRASHED' as RunState,
    Finished: 'FINISHED' as RunState
};

