/**
 * AIoD - RAIL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.20240603-beta
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RunnableDistribution {
  /**
   * The external platform from which this resource originates. Leave empty if this item originates from AIoD. If platform is not None, the platform_resource_identifier should be set as well.
   */
  platform?: string;
  /**
   * A unique identifier issued by the external platform that\'s specified in \'platform\'. Leave empty if this item is not part of an external platform. For example, for HuggingFace, this should be the <namespace>/<dataset_name>, and for Openml, the OpenML identifier.
   */
  platform_resource_identifier?: string;
  /**
   * The value of a checksum algorithm ran on this content.
   */
  checksum?: string;
  /**
   * The checksum algorithm.
   */
  checksum_algorithm?: string;
  copyright?: string;
  content_url?: string;
  content_size_kb?: number;
  /**
   * The datetime (utc) on which this Distribution was first published on an external platform.
   */
  date_published?: string;
  description?: string;
  /**
   * The mimetype of this file.
   */
  encoding_format?: string;
  name?: string;
  /**
   * The technology readiness level (TRL) of the distribution. TRL 1 is the lowest and stands for \'Basic principles observed\', TRL 9 is the highest and stands for \'actual system proven in operational environment\'.
   */
  technology_readiness_level?: number;
  /**
   * An url pointing to a script that can be run to setup the environment necessary for running this distribution. This can be a relative url, if this distribution is a file archive.
   */
  installation_script?: string;
  /**
   * A human readable explanation of the installation, primarily meant as alternative for when there is no installation script.
   */
  installation?: string;
  /**
   * An illustrative time that the installation might typically take.
   */
  installation_time_milliseconds?: number;
  /**
   * An url pointing to a script that can be run to use this resource. This can be a relative url, if this distribution is a file archive.
   */
  deployment_script?: string;
  /**
   * A human readable explanation of the deployment, primarily meant as alternative for when there is no installation script.
   */
  deployment?: string;
  /**
   * An illustrative time that the deployment might typically take.
   */
  deployment_time_milliseconds?: number;
  /**
   * A human readable explanation for the required os.
   */
  os_requirement?: string;
  /**
   * A human readable explanation of (software) dependencies.
   */
  dependency?: string;
  /**
   * A human readable explanation of hardware requirements.
   */
  hardware_requirement?: string;
}

