/**
 * AIoD - RAIL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.20231219-beta
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The size of this dataset, for example the number of rows. The file size should not be included here, but in distribution.content_size_kb.
 */
export interface Size {
    /**
     * Text indicating the unit of measurement.
     */
    unit?: string;
    /**
     * The size.
     */
    value?: number;
}

