/**
 * AIoD - RAIL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.20240603-beta
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type TaskType = 'IMAGE_CLASSIFICATION' | 'OBJECT_DETECTION' | 'TEXT_CLASSIFICATION' | 'TOKEN_CLASSIFICATION' | 'QUESTION_ANSWERING' | 'TRANSLATION' | 'SUMMARIZATION' | 'TEXT_GENERATION' | 'OTHER';

export const TaskType = {
  ImageClassification: 'IMAGE_CLASSIFICATION' as TaskType,
  ObjectDetection: 'OBJECT_DETECTION' as TaskType,
  TextClassification: 'TEXT_CLASSIFICATION' as TaskType,
  TokenClassification: 'TOKEN_CLASSIFICATION' as TaskType,
  QuestionAnswering: 'QUESTION_ANSWERING' as TaskType,
  Translation: 'TRANSLATION' as TaskType,
  Summarization: 'SUMMARIZATION' as TaskType,
  TextGeneration: 'TEXT_GENERATION' as TaskType,
  Other: 'OTHER' as TaskType
};

