/**
 * AIoD - RAIL
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.20240603-beta
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type TemplateState = 'CREATED' | 'IN_PROGRESS' | 'FINISHED' | 'CRASHED';

export const TemplateState = {
  Created: 'CREATED' as TemplateState,
  InProgress: 'IN_PROGRESS' as TemplateState,
  Finished: 'FINISHED' as TemplateState,
  Crashed: 'CRASHED' as TemplateState
};

