/**
 * AIOD - Practitioner\'s Portal
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Location1Inner } from './location1-inner';


export interface ValidationError { 
    loc: Array<Location1Inner>;
    msg: string;
    type: string;
}

