/**
 * AIoD - RAIL
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Location1Inner } from './location1-inner';


export interface ValidationError { 
    loc: Array<Location1Inner>;
    msg: string;
    type: string;
}

