/**
 * AIoD - RAIL
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export const AssetCardinality = {
    _0N: '0-N',
    _1N: '1-N',
    _11: '1-1'
} as const;
export type AssetCardinality = typeof AssetCardinality[keyof typeof AssetCardinality];
