/**
 * AIoD - RAIL
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AIoDEntryRead } from './aio-d-entry-read';
import { Location } from './location';


export interface ContactRead {
    /**
     * The platform from which this resource originates. Defaults to `aiod` for assets registered directly on AI-on-Demand. This field should only be set by connectors, leave empty for users submitting assets. If platform is not None, `platform_resource_identifier` should also be set.
     */
    platform?: string;
    /**
     * The identifier by which the external platform (from `platform`) identifies the asset. Defaults to the asset identifier for assets registered directly on AIoD. This field should only be set by connectors, leave empty for users submitting assets.
     */
    platform_resource_identifier?: string;
    /**
     * The name of this contact, especially useful if it is not known whether this contact is a person or organisation. For persons, it is preferred to store this information as contact.person.surname and contact.person.firstname. For organisations, store it as contact.organisation.legal_name.
     */
    name?: string;
    aiod_entry?: AIoDEntryRead;
    /**
     * An email address.
     */
    email?: Array<string>;
    location?: Array<Location>;
    organisation?: string;
    person?: string;
    /**
     * A telephone number, including the land code.
     */
    telephone?: Array<string>;
    identifier: string;
}
