/**
 * AIoD - RAIL
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export const TaskType = {
    ImageClassification: 'IMAGE_CLASSIFICATION',
    ObjectDetection: 'OBJECT_DETECTION',
    TextClassification: 'TEXT_CLASSIFICATION',
    TokenClassification: 'TOKEN_CLASSIFICATION',
    QuestionAnswering: 'QUESTION_ANSWERING',
    Translation: 'TRANSLATION',
    Summarization: 'SUMMARIZATION',
    TextGeneration: 'TEXT_GENERATION',
    Other: 'OTHER'
} as const;
export type TaskType = typeof TaskType[keyof typeof TaskType];
