/**
 * AIoD - RAIL
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export const TemplateState = {
    Created: 'CREATED',
    InProgress: 'IN_PROGRESS',
    Finished: 'FINISHED',
    Crashed: 'CRASHED'
} as const;
export type TemplateState = typeof TemplateState[keyof typeof TemplateState];
