export const environment = {
  BACKEND_API_URL: 'http://localhost:8000/v1',
  DEFAULT_PAGE_SIZE: 10,
  AIOD_KEYCLOAK_URL: '',
  AIOD_KEYCLOAK_REALM: '',
  AIOD_KEYCLOAK_CLIENT_ID: '',
  AIOD_KEYCLOAK_CLIENT_ID_BACKEND: '',
};
