/**
 * AIoD - RAIL
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Geo {
    /**
     * The latitude of a location in degrees (WGS84)
     */
    latitude?: number;
    /**
     * The longitude of a location in degrees (WGS84)
     */
    longitude?: number;
    /**
     * The elevation in millimeters with tespect to the WGS84 ellipsoid
     */
    elevation_millimeters?: number;
}
