/**
 * AIoD - RAIL
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export const RunState = {
    Created: 'CREATED',
    Preprocessing: "PREPROCESSING",
    Running: "RUNNING",
    Postprocessing: "POSTPROCESSING",
    Finished: 'FINISHED',
    Crashed: 'CRASHED'
} as const;
export type RunState = typeof RunState[keyof typeof RunState];
